// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: game.proto

package server

import (
	"context"

	"dicetales.com/apps/game/rpc/game"
	"dicetales.com/apps/game/rpc/internal/logic"
	"dicetales.com/apps/game/rpc/internal/svc"
)

type GameServer struct {
	svcCtx *svc.ServiceContext
	game.UnimplementedGameServer
}

func NewGameServer(svcCtx *svc.ServiceContext) *GameServer {
	return &GameServer{
		svcCtx: svcCtx,
	}
}

// 获取桌游详细信息
func (s *GameServer) GetGameDetail(ctx context.Context, in *game.GameDetailReq) (*game.GameDetailResp, error) {
	l := logic.NewGetGameDetailLogic(ctx, s.svcCtx)
	return l.GetGameDetail(in)
}

// 分页查询桌游列表
func (s *GameServer) ListGames(ctx context.Context, in *game.ListGamesReq) (*game.ListGamesResp, error) {
	l := logic.NewListGamesLogic(ctx, s.svcCtx)
	return l.ListGames(in)
}

// 获取桌游基础摘要
func (s *GameServer) GetGameBasicInfo(ctx context.Context, in *game.GameBasicInfoReq) (*game.GameBasicInfoResp, error) {
	l := logic.NewGetGameBasicInfoLogic(ctx, s.svcCtx)
	return l.GetGameBasicInfo(in)
}
