// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: game.proto

package server

import (
	"context"

	"dicetales.com/apps/game/rpc/game"
	"dicetales.com/apps/game/rpc/internal/logic"
	"dicetales.com/apps/game/rpc/internal/svc"
)

type GameServer struct {
	svcCtx *svc.ServiceContext
	game.UnimplementedGameServer
}

func NewGameServer(svcCtx *svc.ServiceContext) *GameServer {
	return &GameServer{
		svcCtx: svcCtx,
	}
}

// 获取桌游详细信息
func (s *GameServer) GetGameDetail(ctx context.Context, in *game.GetGameDetailReq) (*game.GetGameDetailResp, error) {
	l := logic.NewGetGameDetailLogic(ctx, s.svcCtx)
	return l.GetGameDetail(in)
}

// 高级组合筛选 (核心亮点)
func (s *GameServer) FilterGames(ctx context.Context, in *game.FilterGamesReq) (*game.FilterGamesResp, error) {
	l := logic.NewFilterGamesLogic(ctx, s.svcCtx)
	return l.FilterGames(in)
}

// 模糊搜索
func (s *GameServer) SearchGames(ctx context.Context, in *game.SearchGamesReq) (*game.SearchGamesResp, error) {
	l := logic.NewSearchGamesLogic(ctx, s.svcCtx)
	return l.SearchGames(in)
}

// 批量拉取桌游轻量摘要
func (s *GameServer) GetGameBasicInfo(ctx context.Context, in *game.GetGameBasicInfoReq) (*game.GetGameBasicInfoResp, error) {
	l := logic.NewGetGameBasicInfoLogic(ctx, s.svcCtx)
	return l.GetGameBasicInfo(in)
}
