// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameTagRelationFieldNames          = builder.RawFieldNames(&GameTagRelation{})
	gameTagRelationRows                = strings.Join(gameTagRelationFieldNames, ",")
	gameTagRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(gameTagRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameTagRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(gameTagRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGameTagRelationIdPrefix          = "cache:gameTagRelation:id:"
	cacheGameTagRelationGameIdTagIdPrefix = "cache:gameTagRelation:gameId:tagId:"
)

type (
	gameTagRelationModel interface {
		Insert(ctx context.Context, data *GameTagRelation) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameTagRelation, error)
		FindOneByGameIdTagId(ctx context.Context, gameId uint64, tagId uint64) (*GameTagRelation, error)
		Update(ctx context.Context, data *GameTagRelation) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameTagRelationModel struct {
		sqlc.CachedConn
		table string
	}

	GameTagRelation struct {
		Id        uint64    `db:"id"`
		GameId    uint64    `db:"game_id"`
		TagId     uint64    `db:"tag_id"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newGameTagRelationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameTagRelationModel {
	return &defaultGameTagRelationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_tag_relation`",
	}
}

func (m *defaultGameTagRelationModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	gameTagRelationGameIdTagIdKey := fmt.Sprintf("%s%v:%v", cacheGameTagRelationGameIdTagIdPrefix, data.GameId, data.TagId)
	gameTagRelationIdKey := fmt.Sprintf("%s%v", cacheGameTagRelationIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gameTagRelationGameIdTagIdKey, gameTagRelationIdKey)
	return err
}

func (m *defaultGameTagRelationModel) FindOne(ctx context.Context, id uint64) (*GameTagRelation, error) {
	gameTagRelationIdKey := fmt.Sprintf("%s%v", cacheGameTagRelationIdPrefix, id)
	var resp GameTagRelation
	err := m.QueryRowCtx(ctx, &resp, gameTagRelationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameTagRelationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTagRelationModel) FindOneByGameIdTagId(ctx context.Context, gameId uint64, tagId uint64) (*GameTagRelation, error) {
	gameTagRelationGameIdTagIdKey := fmt.Sprintf("%s%v:%v", cacheGameTagRelationGameIdTagIdPrefix, gameId, tagId)
	var resp GameTagRelation
	err := m.QueryRowIndexCtx(ctx, &resp, gameTagRelationGameIdTagIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `game_id` = ? and `tag_id` = ? limit 1", gameTagRelationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, gameId, tagId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTagRelationModel) Insert(ctx context.Context, data *GameTagRelation) (sql.Result, error) {
	gameTagRelationGameIdTagIdKey := fmt.Sprintf("%s%v:%v", cacheGameTagRelationGameIdTagIdPrefix, data.GameId, data.TagId)
	gameTagRelationIdKey := fmt.Sprintf("%s%v", cacheGameTagRelationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, gameTagRelationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GameId, data.TagId)
	}, gameTagRelationGameIdTagIdKey, gameTagRelationIdKey)
	return ret, err
}

func (m *defaultGameTagRelationModel) Update(ctx context.Context, newData *GameTagRelation) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	gameTagRelationGameIdTagIdKey := fmt.Sprintf("%s%v:%v", cacheGameTagRelationGameIdTagIdPrefix, data.GameId, data.TagId)
	gameTagRelationIdKey := fmt.Sprintf("%s%v", cacheGameTagRelationIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameTagRelationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GameId, newData.TagId, newData.Id)
	}, gameTagRelationGameIdTagIdKey, gameTagRelationIdKey)
	return err
}

func (m *defaultGameTagRelationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGameTagRelationIdPrefix, primary)
}

func (m *defaultGameTagRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameTagRelationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameTagRelationModel) tableName() string {
	return m.table
}
