// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameFieldNames          = builder.RawFieldNames(&Game{})
	gameRows                = strings.Join(gameFieldNames, ",")
	gameRowsExpectAutoSet   = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameRowsWithPlaceHolder = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGameIdPrefix = "cache:game:id:"
)

type (
	gameModel interface {
		Insert(ctx context.Context, data *Game) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Game, error)
		Update(ctx context.Context, data *Game) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameModel struct {
		sqlc.CachedConn
		table string
	}

	Game struct {
		Id                    uint64          `db:"id"`
		Name                  string          `db:"name"`                    // 中文名
		NameEn                sql.NullString  `db:"name_en"`                 // 英文名
		CoverImg              sql.NullString  `db:"cover_img"`               // 封面图URL
		Score                 float64         `db:"score"`                   // 评分
		ScoreCount            int64           `db:"score_count"`             // 打分人数
		MinPlayers            int64           `db:"min_players"`             // 最少人数
		MaxPlayers            int64           `db:"max_players"`             // 最多人数
		MinRecommendedPlayers sql.NullInt64   `db:"min_recommended_players"` // 最少推荐人数
		MaxRecommendedPlayers sql.NullInt64   `db:"max_recommended_players"` // 最多推荐人数
		NeedHost              int64           `db:"need_host"`               // 是否需要主持人 0-否 1-是
		Rank                  sql.NullInt64   `db:"rank"`                    // 排行榜名次
		Year                  sql.NullInt64   `db:"year"`                    // 发行年份
		Description           sql.NullString  `db:"description"`             // 桌游简介
		Difficulty            sql.NullFloat64 `db:"difficulty"`              // 上手难度(满分10级)
		DurationPerPlayer     sql.NullInt64   `db:"duration_per_player"`     // 人均时长(分钟)
		SetupTime             sql.NullString  `db:"setup_time"`              // 设置时长
		LanguageDependency    sql.NullString  `db:"language_dependency"`     // 语言需求文本描述，例如：较高
		CreatedAt             time.Time       `db:"created_at"`
		UpdatedAt             time.Time       `db:"updated_at"`
	}
)

func newGameModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameModel {
	return &defaultGameModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game`",
	}
}

func (m *defaultGameModel) Delete(ctx context.Context, id uint64) error {
	gameIdKey := fmt.Sprintf("%s%v", cacheGameIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gameIdKey)
	return err
}

func (m *defaultGameModel) FindOne(ctx context.Context, id uint64) (*Game, error) {
	gameIdKey := fmt.Sprintf("%s%v", cacheGameIdPrefix, id)
	var resp Game
	err := m.QueryRowCtx(ctx, &resp, gameIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameModel) Insert(ctx context.Context, data *Game) (sql.Result, error) {
	gameIdKey := fmt.Sprintf("%s%v", cacheGameIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.NameEn, data.CoverImg, data.Score, data.ScoreCount, data.MinPlayers, data.MaxPlayers, data.MinRecommendedPlayers, data.MaxRecommendedPlayers, data.NeedHost, data.Rank, data.Year, data.Description, data.Difficulty, data.DurationPerPlayer, data.SetupTime, data.LanguageDependency)
	}, gameIdKey)
	return ret, err
}

func (m *defaultGameModel) Update(ctx context.Context, data *Game) error {
	gameIdKey := fmt.Sprintf("%s%v", cacheGameIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.NameEn, data.CoverImg, data.Score, data.ScoreCount, data.MinPlayers, data.MaxPlayers, data.MinRecommendedPlayers, data.MaxRecommendedPlayers, data.NeedHost, data.Rank, data.Year, data.Description, data.Difficulty, data.DurationPerPlayer, data.SetupTime, data.LanguageDependency, data.Id)
	}, gameIdKey)
	return err
}

func (m *defaultGameModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGameIdPrefix, primary)
}

func (m *defaultGameModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameModel) tableName() string {
	return m.table
}
