// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameResourceFieldNames          = builder.RawFieldNames(&GameResource{})
	gameResourceRows                = strings.Join(gameResourceFieldNames, ",")
	gameResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(gameResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(gameResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGameResourceIdPrefix = "cache:gameResource:id:"
)

type (
	gameResourceModel interface {
		Insert(ctx context.Context, data *GameResource) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameResource, error)
		Update(ctx context.Context, data *GameResource) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameResourceModel struct {
		sqlc.CachedConn
		table string
	}

	GameResource struct {
		Id        uint64    `db:"id"`
		GameId    uint64    `db:"game_id"` // 桌游ID
		Type      int64     `db:"type"`    // 资源类型 1:规则书 2:教学视频 3:扩展包
		Title     string    `db:"title"`   // 资源标题
		Url       string    `db:"url"`     // 资源链接
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newGameResourceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameResourceModel {
	return &defaultGameResourceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_resource`",
	}
}

func (m *defaultGameResourceModel) Delete(ctx context.Context, id uint64) error {
	gameResourceIdKey := fmt.Sprintf("%s%v", cacheGameResourceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gameResourceIdKey)
	return err
}

func (m *defaultGameResourceModel) FindOne(ctx context.Context, id uint64) (*GameResource, error) {
	gameResourceIdKey := fmt.Sprintf("%s%v", cacheGameResourceIdPrefix, id)
	var resp GameResource
	err := m.QueryRowCtx(ctx, &resp, gameResourceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameResourceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameResourceModel) Insert(ctx context.Context, data *GameResource) (sql.Result, error) {
	gameResourceIdKey := fmt.Sprintf("%s%v", cacheGameResourceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, gameResourceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GameId, data.Type, data.Title, data.Url)
	}, gameResourceIdKey)
	return ret, err
}

func (m *defaultGameResourceModel) Update(ctx context.Context, data *GameResource) error {
	gameResourceIdKey := fmt.Sprintf("%s%v", cacheGameResourceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameResourceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.GameId, data.Type, data.Title, data.Url, data.Id)
	}, gameResourceIdKey)
	return err
}

func (m *defaultGameResourceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGameResourceIdPrefix, primary)
}

func (m *defaultGameResourceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameResourceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameResourceModel) tableName() string {
	return m.table
}
