// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameCategoryInfoFieldNames          = builder.RawFieldNames(&GameCategoryInfo{})
	gameCategoryInfoRows                = strings.Join(gameCategoryInfoFieldNames, ",")
	gameCategoryInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(gameCategoryInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameCategoryInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(gameCategoryInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGameCategoryInfoIdPrefix     = "cache:gameCategoryInfo:id:"
	cacheGameCategoryInfoGameIdPrefix = "cache:gameCategoryInfo:gameId:"
)

type (
	gameCategoryInfoModel interface {
		Insert(ctx context.Context, data *GameCategoryInfo) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GameCategoryInfo, error)
		FindOneByGameId(ctx context.Context, gameId uint64) (*GameCategoryInfo, error)
		Update(ctx context.Context, data *GameCategoryInfo) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGameCategoryInfoModel struct {
		sqlc.CachedConn
		table string
	}

	GameCategoryInfo struct {
		Id               uint64         `db:"id"`
		GameId           uint64         `db:"game_id"`           // 桌游ID，关联game表的id
		Category         sql.NullString `db:"category"`          // 游戏类别
		Mode             sql.NullString `db:"mode"`              // 游戏模式
		Theme            sql.NullString `db:"theme"`             // 游戏主题
		Mechanic         sql.NullString `db:"mechanic"`          // 游戏机制
		Portability      sql.NullString `db:"portability"`       // 便携程度
		TableRequirement sql.NullString `db:"table_requirement"` // 桌面要求
		SuitableAge      sql.NullInt64  `db:"suitable_age"`      // 适合年龄
		CreatedAt        time.Time      `db:"created_at"`
		UpdatedAt        time.Time      `db:"updated_at"`
	}
)

func newGameCategoryInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGameCategoryInfoModel {
	return &defaultGameCategoryInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`game_category_info`",
	}
}

func (m *defaultGameCategoryInfoModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	gameCategoryInfoGameIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoGameIdPrefix, data.GameId)
	gameCategoryInfoIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gameCategoryInfoGameIdKey, gameCategoryInfoIdKey)
	return err
}

func (m *defaultGameCategoryInfoModel) FindOne(ctx context.Context, id uint64) (*GameCategoryInfo, error) {
	gameCategoryInfoIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoIdPrefix, id)
	var resp GameCategoryInfo
	err := m.QueryRowCtx(ctx, &resp, gameCategoryInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameCategoryInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameCategoryInfoModel) FindOneByGameId(ctx context.Context, gameId uint64) (*GameCategoryInfo, error) {
	gameCategoryInfoGameIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoGameIdPrefix, gameId)
	var resp GameCategoryInfo
	err := m.QueryRowIndexCtx(ctx, &resp, gameCategoryInfoGameIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `game_id` = ? limit 1", gameCategoryInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, gameId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameCategoryInfoModel) Insert(ctx context.Context, data *GameCategoryInfo) (sql.Result, error) {
	gameCategoryInfoGameIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoGameIdPrefix, data.GameId)
	gameCategoryInfoIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameCategoryInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GameId, data.Category, data.Mode, data.Theme, data.Mechanic, data.Portability, data.TableRequirement, data.SuitableAge)
	}, gameCategoryInfoGameIdKey, gameCategoryInfoIdKey)
	return ret, err
}

func (m *defaultGameCategoryInfoModel) Update(ctx context.Context, newData *GameCategoryInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	gameCategoryInfoGameIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoGameIdPrefix, data.GameId)
	gameCategoryInfoIdKey := fmt.Sprintf("%s%v", cacheGameCategoryInfoIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameCategoryInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GameId, newData.Category, newData.Mode, newData.Theme, newData.Mechanic, newData.Portability, newData.TableRequirement, newData.SuitableAge, newData.Id)
	}, gameCategoryInfoGameIdKey, gameCategoryInfoIdKey)
	return err
}

func (m *defaultGameCategoryInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGameCategoryInfoIdPrefix, primary)
}

func (m *defaultGameCategoryInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameCategoryInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameCategoryInfoModel) tableName() string {
	return m.table
}
