// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTagIdPrefix           = "cache:tag:id:"
	cacheTagNameCategoryPrefix = "cache:tag:name:category:"
)

type (
	tagModel interface {
		Insert(ctx context.Context, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tag, error)
		FindOneByNameCategory(ctx context.Context, name string, category int64) (*Tag, error)
		Update(ctx context.Context, data *Tag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTagModel struct {
		sqlc.CachedConn
		table string
	}

	Tag struct {
		Id        uint64    `db:"id"`
		Name      string    `db:"name"`     // 标签名
		Category  int64     `db:"category"` // 类型 1:机制 2:主题 3:分类
		CreatedAt time.Time `db:"created_at"`
	}
)

func newTagModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTagModel {
	return &defaultTagModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tag`",
	}
}

func (m *defaultTagModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tagIdKey := fmt.Sprintf("%s%v", cacheTagIdPrefix, id)
	tagNameCategoryKey := fmt.Sprintf("%s%v:%v", cacheTagNameCategoryPrefix, data.Name, data.Category)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tagIdKey, tagNameCategoryKey)
	return err
}

func (m *defaultTagModel) FindOne(ctx context.Context, id uint64) (*Tag, error) {
	tagIdKey := fmt.Sprintf("%s%v", cacheTagIdPrefix, id)
	var resp Tag
	err := m.QueryRowCtx(ctx, &resp, tagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) FindOneByNameCategory(ctx context.Context, name string, category int64) (*Tag, error) {
	tagNameCategoryKey := fmt.Sprintf("%s%v:%v", cacheTagNameCategoryPrefix, name, category)
	var resp Tag
	err := m.QueryRowIndexCtx(ctx, &resp, tagNameCategoryKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? and `category` = ? limit 1", tagRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name, category); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, data *Tag) (sql.Result, error) {
	tagIdKey := fmt.Sprintf("%s%v", cacheTagIdPrefix, data.Id)
	tagNameCategoryKey := fmt.Sprintf("%s%v:%v", cacheTagNameCategoryPrefix, data.Name, data.Category)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, tagRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Category)
	}, tagIdKey, tagNameCategoryKey)
	return ret, err
}

func (m *defaultTagModel) Update(ctx context.Context, newData *Tag) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tagIdKey := fmt.Sprintf("%s%v", cacheTagIdPrefix, data.Id)
	tagNameCategoryKey := fmt.Sprintf("%s%v:%v", cacheTagNameCategoryPrefix, data.Name, data.Category)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tagRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Category, newData.Id)
	}, tagIdKey, tagNameCategoryKey)
	return err
}

func (m *defaultTagModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTagIdPrefix, primary)
}

func (m *defaultTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
