// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	game "dicetales.com/apps/api/internal/handler/game"
	meetup "dicetales.com/apps/api/internal/handler/meetup"
	post "dicetales.com/apps/api/internal/handler/post"
	social "dicetales.com/apps/api/internal/handler/social"
	user "dicetales.com/apps/api/internal/handler/user"
	"dicetales.com/apps/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Game Module Placeholder
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: game.GamePingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/game"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Meetup Module Placeholder
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: meetup.MeetupPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/meetup"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Post Module Placeholder
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: post.PostPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Social Module Placeholder
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: social.SocialPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登入
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// 刷新Token
				Method:  http.MethodPost,
				Path:    "/token/refresh",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/user"),
	)
}
