// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: im.proto

package imclient

import (
	"context"

	"dicetales.com/apps/im/rpc/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AckMessageReadReq         = im.AckMessageReadReq
	AckMessageReadResp        = im.AckMessageReadResp
	ChatLog                   = im.ChatLog
	Conversation              = im.Conversation
	GetChatLogReq             = im.GetChatLogReq
	GetChatLogResp            = im.GetChatLogResp
	GetConversationsReq       = im.GetConversationsReq
	GetConversationsResp      = im.GetConversationsResp
	PutChatLogReq             = im.PutChatLogReq
	PutChatLogResp            = im.PutChatLogResp
	SetUpUserConversationReq  = im.SetUpUserConversationReq
	SetUpUserConversationResp = im.SetUpUserConversationResp

	Im interface {
		SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error)
		PutChatLog(ctx context.Context, in *PutChatLogReq, opts ...grpc.CallOption) (*PutChatLogResp, error)
		GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
		GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error)
		AckMessageRead(ctx context.Context, in *AckMessageReadReq, opts ...grpc.CallOption) (*AckMessageReadResp, error)
	}

	defaultIm struct {
		cli zrpc.Client
	}
)

func NewIm(cli zrpc.Client) Im {
	return &defaultIm{
		cli: cli,
	}
}

func (m *defaultIm) SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...grpc.CallOption) (*SetUpUserConversationResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.SetUpUserConversation(ctx, in, opts...)
}

func (m *defaultIm) PutChatLog(ctx context.Context, in *PutChatLogReq, opts ...grpc.CallOption) (*PutChatLogResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.PutChatLog(ctx, in, opts...)
}

func (m *defaultIm) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

func (m *defaultIm) GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...grpc.CallOption) (*GetChatLogResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.GetChatLog(ctx, in, opts...)
}

func (m *defaultIm) AckMessageRead(ctx context.Context, in *AckMessageReadReq, opts ...grpc.CallOption) (*AckMessageReadResp, error) {
	client := im.NewImClient(m.cli.Conn())
	return client.AckMessageRead(ctx, in, opts...)
}
