// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: social.proto

package server

import (
	"context"

	"dicetales.com/apps/social/rpc/internal/logic"
	"dicetales.com/apps/social/rpc/internal/svc"
	"dicetales.com/apps/social/rpc/social"
)

type SocialServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedSocialServer
}

func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// 好友业务：请求好友、通过或拒绝申请、好友列表
func (s *SocialServer) FriendPutIn(ctx context.Context, in *social.FriendPutInReq) (*social.FriendPutInResp, error) {
	l := logic.NewFriendPutInLogic(ctx, s.svcCtx)
	return l.FriendPutIn(in)
}

func (s *SocialServer) FriendPutInHandle(ctx context.Context, in *social.FriendPutInHandleReq) (*social.FriendPutInHandleResp, error) {
	l := logic.NewFriendPutInHandleLogic(ctx, s.svcCtx)
	return l.FriendPutInHandle(in)
}

func (s *SocialServer) FriendPutInList(ctx context.Context, in *social.FriendPutInListReq) (*social.FriendPutInListResp, error) {
	l := logic.NewFriendPutInListLogic(ctx, s.svcCtx)
	return l.FriendPutInList(in)
}

func (s *SocialServer) FriendList(ctx context.Context, in *social.FriendListReq) (*social.FriendListResp, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

func (s *SocialServer) FriendDelete(ctx context.Context, in *social.FriendDeleteReq) (*social.FriendDeleteResp, error) {
	l := logic.NewFriendDeleteLogic(ctx, s.svcCtx)
	return l.FriendDelete(in)
}

// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，群退出..
func (s *SocialServer) GroupCreate(ctx context.Context, in *social.GroupCreateReq) (*social.GroupCreateResp, error) {
	l := logic.NewGroupCreateLogic(ctx, s.svcCtx)
	return l.GroupCreate(in)
}

func (s *SocialServer) GroupPutin(ctx context.Context, in *social.GroupPutinReq) (*social.GroupPutinResp, error) {
	l := logic.NewGroupPutinLogic(ctx, s.svcCtx)
	return l.GroupPutin(in)
}

func (s *SocialServer) GroupPutinList(ctx context.Context, in *social.GroupPutinListReq) (*social.GroupPutinListResp, error) {
	l := logic.NewGroupPutinListLogic(ctx, s.svcCtx)
	return l.GroupPutinList(in)
}

func (s *SocialServer) GroupUserReqList(ctx context.Context, in *social.GroupUserReqListReq) (*social.GroupUserReqListResp, error) {
	l := logic.NewGroupUserReqListLogic(ctx, s.svcCtx)
	return l.GroupUserReqList(in)
}

func (s *SocialServer) GroupPutInHandle(ctx context.Context, in *social.GroupPutInHandleReq) (*social.GroupPutInHandleResp, error) {
	l := logic.NewGroupPutInHandleLogic(ctx, s.svcCtx)
	return l.GroupPutInHandle(in)
}

func (s *SocialServer) GroupList(ctx context.Context, in *social.GroupListReq) (*social.GroupListResp, error) {
	l := logic.NewGroupListLogic(ctx, s.svcCtx)
	return l.GroupList(in)
}

func (s *SocialServer) GroupMember(ctx context.Context, in *social.GroupMemberReq) (*social.GroupMemberResp, error) {
	l := logic.NewGroupMemberLogic(ctx, s.svcCtx)
	return l.GroupMember(in)
}

func (s *SocialServer) GroupQuit(ctx context.Context, in *social.GroupQuitReq) (*social.GroupQuitResp, error) {
	l := logic.NewGroupQuitLogic(ctx, s.svcCtx)
	return l.GroupQuit(in)
}

func (s *SocialServer) GroupModify(ctx context.Context, in *social.GroupModifyReq) (*social.GroupModifyResp, error) {
	l := logic.NewGroupModifyLogic(ctx, s.svcCtx)
	return l.GroupModify(in)
}

func (s *SocialServer) GroupNotificationModify(ctx context.Context, in *social.GroupNotificationModifyReq) (*social.GroupNotificationModifyResp, error) {
	l := logic.NewGroupNotificationModifyLogic(ctx, s.svcCtx)
	return l.GroupNotificationModify(in)
}
