// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: im.proto

package server

import (
	"context"

	"dicetales.com/apps/im/rpc/im"
	"dicetales.com/apps/im/rpc/internal/logic"
	"dicetales.com/apps/im/rpc/internal/svc"
)

type ImServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedImServer
}

func NewImServer(svcCtx *svc.ServiceContext) *ImServer {
	return &ImServer{
		svcCtx: svcCtx,
	}
}

func (s *ImServer) SetUpUserConversation(ctx context.Context, in *im.SetUpUserConversationReq) (*im.SetUpUserConversationResp, error) {
	l := logic.NewSetUpUserConversationLogic(ctx, s.svcCtx)
	return l.SetUpUserConversation(in)
}

func (s *ImServer) PutChatLog(ctx context.Context, in *im.PutChatLogReq) (*im.PutChatLogResp, error) {
	l := logic.NewPutChatLogLogic(ctx, s.svcCtx)
	return l.PutChatLog(in)
}

func (s *ImServer) GetConversations(ctx context.Context, in *im.GetConversationsReq) (*im.GetConversationsResp, error) {
	l := logic.NewGetConversationsLogic(ctx, s.svcCtx)
	return l.GetConversations(in)
}

func (s *ImServer) GetChatLog(ctx context.Context, in *im.GetChatLogReq) (*im.GetChatLogResp, error) {
	l := logic.NewGetChatLogLogic(ctx, s.svcCtx)
	return l.GetChatLog(in)
}

func (s *ImServer) AckMessageRead(ctx context.Context, in *im.AckMessageReadReq) (*im.AckMessageReadResp, error) {
	l := logic.NewAckMessageReadLogic(ctx, s.svcCtx)
	return l.AckMessageRead(in)
}
