FROM alpine:3.22.2

# 时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.22/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone
ENV TZ=Asia/Shanghai

ARG SERVER_NAME=game
ARG SERVER_TYPE=rpc

ENV RUN_BIN=bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF=/${SERVER_NAME}/conf/${SERVER_NAME}.yaml

RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/

COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/$SERVER_NAME.yaml /$SERVER_NAME/conf/

RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME

ENTRYPOINT ["/game/bin/game-rpc"]
