# ============== Stage 1: Build =================
FROM golang:alpine AS builder
# 可选：如果网络不佳，可配置代理
# ENV GOPROXY=https://goproxy.cn,direct

WORKDIR /app
# 优先复制 go.mod 和 go.sum 缓存层
COPY go.mod go.sum ./
RUN go mod download

# 复制整个项目源码
COPY . .

# 编译参数
ARG SERVER_NAME=user
ARG SERVER_TYPE=rpc

# 在容器内进行静态编译
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o /app/bin/${SERVER_NAME}-${SERVER_TYPE} ./apps/${SERVER_NAME}/${SERVER_TYPE}/${SERVER_NAME}.go

# ============== Stage 2: Run =================
FROM alpine:3.22.2

# 时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.22/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone
ENV TZ=Asia/Shanghai

ARG SERVER_NAME=user
ARG SERVER_TYPE=rpc

ENV RUN_BIN=bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF=/${SERVER_NAME}/conf/${SERVER_NAME}.yaml

RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

# 🎉 这里是重点：从 builder 阶段复制已经编译好的二进制文件
COPY --from=builder /app/bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/

COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/$SERVER_NAME.yaml /$SERVER_NAME/conf/

RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME

ENTRYPOINT ["/user/bin/user-rpc"]
CMD ["-f", "/user/conf/user.yaml"]