// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: social.proto

package socialclient

import (
	"context"

	"dicetales.com/apps/social/rpc/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Friend                      = social.Friend
	FriendDeleteReq             = social.FriendDeleteReq
	FriendDeleteResp            = social.FriendDeleteResp
	FriendListReq               = social.FriendListReq
	FriendListResp              = social.FriendListResp
	FriendPutInHandleReq        = social.FriendPutInHandleReq
	FriendPutInHandleResp       = social.FriendPutInHandleResp
	FriendPutInListReq          = social.FriendPutInListReq
	FriendPutInListResp         = social.FriendPutInListResp
	FriendPutInReq              = social.FriendPutInReq
	FriendPutInResp             = social.FriendPutInResp
	FriendRequest               = social.FriendRequest
	Group                       = social.Group
	GroupCreateReq              = social.GroupCreateReq
	GroupCreateResp             = social.GroupCreateResp
	GroupListReq                = social.GroupListReq
	GroupListResp               = social.GroupListResp
	GroupMember                 = social.GroupMember
	GroupMemberReq              = social.GroupMemberReq
	GroupMemberResp             = social.GroupMemberResp
	GroupModifyReq              = social.GroupModifyReq
	GroupModifyResp             = social.GroupModifyResp
	GroupNotificationModifyReq  = social.GroupNotificationModifyReq
	GroupNotificationModifyResp = social.GroupNotificationModifyResp
	GroupPutInHandleReq         = social.GroupPutInHandleReq
	GroupPutInHandleResp        = social.GroupPutInHandleResp
	GroupPutinListReq           = social.GroupPutinListReq
	GroupPutinListResp          = social.GroupPutinListResp
	GroupPutinReq               = social.GroupPutinReq
	GroupPutinResp              = social.GroupPutinResp
	GroupQuitReq                = social.GroupQuitReq
	GroupQuitResp               = social.GroupQuitResp
	GroupRequest                = social.GroupRequest
	GroupUserReqListReq         = social.GroupUserReqListReq
	GroupUserReqListResp        = social.GroupUserReqListResp

	Social interface {
		// 好友业务：请求好友、通过或拒绝申请、好友列表
		FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error)
		FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error)
		FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error)
		FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error)
		FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error)
		// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，群退出..
		GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error)
		GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error)
		GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error)
		GroupUserReqList(ctx context.Context, in *GroupUserReqListReq, opts ...grpc.CallOption) (*GroupUserReqListResp, error)
		GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error)
		GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error)
		GroupMember(ctx context.Context, in *GroupMemberReq, opts ...grpc.CallOption) (*GroupMemberResp, error)
		GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error)
		GroupModify(ctx context.Context, in *GroupModifyReq, opts ...grpc.CallOption) (*GroupModifyResp, error)
		GroupNotificationModify(ctx context.Context, in *GroupNotificationModifyReq, opts ...grpc.CallOption) (*GroupNotificationModifyResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 好友业务：请求好友、通过或拒绝申请、好友列表
func (m *defaultSocial) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...grpc.CallOption) (*FriendPutInResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutIn(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...grpc.CallOption) (*FriendPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...grpc.CallOption) (*FriendPutInListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendPutInList(ctx, in, opts...)
}

func (m *defaultSocial) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

func (m *defaultSocial) FriendDelete(ctx context.Context, in *FriendDeleteReq, opts ...grpc.CallOption) (*FriendDeleteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FriendDelete(ctx, in, opts...)
}

// 群业务：创建群，修改群，群公告，申请群，用户群列表，群成员，群退出..
func (m *defaultSocial) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...grpc.CallOption) (*GroupCreateResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupCreate(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...grpc.CallOption) (*GroupPutinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutin(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...grpc.CallOption) (*GroupPutinListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutinList(ctx, in, opts...)
}

func (m *defaultSocial) GroupUserReqList(ctx context.Context, in *GroupUserReqListReq, opts ...grpc.CallOption) (*GroupUserReqListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupUserReqList(ctx, in, opts...)
}

func (m *defaultSocial) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...grpc.CallOption) (*GroupPutInHandleResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupPutInHandle(ctx, in, opts...)
}

func (m *defaultSocial) GroupList(ctx context.Context, in *GroupListReq, opts ...grpc.CallOption) (*GroupListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupList(ctx, in, opts...)
}

func (m *defaultSocial) GroupMember(ctx context.Context, in *GroupMemberReq, opts ...grpc.CallOption) (*GroupMemberResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupMember(ctx, in, opts...)
}

func (m *defaultSocial) GroupQuit(ctx context.Context, in *GroupQuitReq, opts ...grpc.CallOption) (*GroupQuitResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupQuit(ctx, in, opts...)
}

func (m *defaultSocial) GroupModify(ctx context.Context, in *GroupModifyReq, opts ...grpc.CallOption) (*GroupModifyResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupModify(ctx, in, opts...)
}

func (m *defaultSocial) GroupNotificationModify(ctx context.Context, in *GroupNotificationModifyReq, opts ...grpc.CallOption) (*GroupNotificationModifyResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GroupNotificationModify(ctx, in, opts...)
}
