// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: im.proto

package im

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. 设置/建立会话
type SetUpUserConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendId        string                 `protobuf:"bytes,1,opt,name=sendId,proto3" json:"sendId,omitempty"`
	RecvId        string                 `protobuf:"bytes,2,opt,name=recvId,proto3" json:"recvId,omitempty"`
	ChatType      int32                  `protobuf:"varint,3,opt,name=chatType,proto3" json:"chatType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpUserConversationReq) Reset() {
	*x = SetUpUserConversationReq{}
	mi := &file_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpUserConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpUserConversationReq) ProtoMessage() {}

func (x *SetUpUserConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpUserConversationReq.ProtoReflect.Descriptor instead.
func (*SetUpUserConversationReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *SetUpUserConversationReq) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *SetUpUserConversationReq) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *SetUpUserConversationReq) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

type SetUpUserConversationResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetUpUserConversationResp) Reset() {
	*x = SetUpUserConversationResp{}
	mi := &file_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpUserConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpUserConversationResp) ProtoMessage() {}

func (x *SetUpUserConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpUserConversationResp.ProtoReflect.Descriptor instead.
func (*SetUpUserConversationResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

func (x *SetUpUserConversationResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 2. 存储聊天记录 (聊天持久化)
type PutChatLogReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SendId         string                 `protobuf:"bytes,2,opt,name=sendId,proto3" json:"sendId,omitempty"`
	RecvId         string                 `protobuf:"bytes,3,opt,name=recvId,proto3" json:"recvId,omitempty"`
	ChatType       int32                  `protobuf:"varint,4,opt,name=chatType,proto3" json:"chatType,omitempty"`
	MsgType        int32                  `protobuf:"varint,5,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgContent     string                 `protobuf:"bytes,6,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
	MsgId          string                 `protobuf:"bytes,7,opt,name=msgId,proto3" json:"msgId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutChatLogReq) Reset() {
	*x = PutChatLogReq{}
	mi := &file_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChatLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChatLogReq) ProtoMessage() {}

func (x *PutChatLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChatLogReq.ProtoReflect.Descriptor instead.
func (*PutChatLogReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *PutChatLogReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PutChatLogReq) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *PutChatLogReq) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *PutChatLogReq) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *PutChatLogReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PutChatLogReq) GetMsgContent() string {
	if x != nil {
		return x.MsgContent
	}
	return ""
}

func (x *PutChatLogReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type PutChatLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	SendTime      int64                  `protobuf:"varint,3,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChatLogResp) Reset() {
	*x = PutChatLogResp{}
	mi := &file_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChatLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChatLogResp) ProtoMessage() {}

func (x *PutChatLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChatLogResp.ProtoReflect.Descriptor instead.
func (*PutChatLogResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *PutChatLogResp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PutChatLogResp) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PutChatLogResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

// 3. 获取最新会话列表
type GetConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsReq) Reset() {
	*x = GetConversationsReq{}
	mi := &file_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsReq) ProtoMessage() {}

func (x *GetConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsReq.ProtoReflect.Descriptor instead.
func (*GetConversationsReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationsReq) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ChatType       int32                  `protobuf:"varint,2,opt,name=chatType,proto3" json:"chatType,omitempty"`
	MaxSeq         int64                  `protobuf:"varint,3,opt,name=maxSeq,proto3" json:"maxSeq,omitempty"`
	LatestMsg      string                 `protobuf:"bytes,4,opt,name=latestMsg,proto3" json:"latestMsg,omitempty"`
	LastMsgTime    int64                  `protobuf:"varint,5,opt,name=lastMsgTime,proto3" json:"lastMsgTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *Conversation) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Conversation) GetLatestMsg() string {
	if x != nil {
		return x.LatestMsg
	}
	return ""
}

func (x *Conversation) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

type GetConversationsResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationList []*Conversation        `protobuf:"bytes,1,rep,name=conversationList,proto3" json:"conversationList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConversationsResp) Reset() {
	*x = GetConversationsResp{}
	mi := &file_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsResp) ProtoMessage() {}

func (x *GetConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsResp.ProtoReflect.Descriptor instead.
func (*GetConversationsResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationsResp) GetConversationList() []*Conversation {
	if x != nil {
		return x.ConversationList
	}
	return nil
}

// 4. 获取聊天记录 (游标拉取)
type GetChatLogReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	CursorTime     int64                  `protobuf:"varint,2,opt,name=cursorTime,proto3" json:"cursorTime,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChatLogReq) Reset() {
	*x = GetChatLogReq{}
	mi := &file_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatLogReq) ProtoMessage() {}

func (x *GetChatLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatLogReq.ProtoReflect.Descriptor instead.
func (*GetChatLogReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatLogReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetChatLogReq) GetCursorTime() int64 {
	if x != nil {
		return x.CursorTime
	}
	return 0
}

func (x *GetChatLogReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChatLog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	SendId         string                 `protobuf:"bytes,4,opt,name=sendId,proto3" json:"sendId,omitempty"`
	RecvId         string                 `protobuf:"bytes,5,opt,name=recvId,proto3" json:"recvId,omitempty"`
	MsgType        int32                  `protobuf:"varint,6,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgContent     string                 `protobuf:"bytes,7,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
	SendTime       int64                  `protobuf:"varint,8,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatLog) Reset() {
	*x = ChatLog{}
	mi := &file_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatLog) ProtoMessage() {}

func (x *ChatLog) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatLog.ProtoReflect.Descriptor instead.
func (*ChatLog) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{8}
}

func (x *ChatLog) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ChatLog) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatLog) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *ChatLog) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *ChatLog) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *ChatLog) GetMsgContent() string {
	if x != nil {
		return x.MsgContent
	}
	return ""
}

func (x *ChatLog) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type GetChatLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatLogList   []*ChatLog             `protobuf:"bytes,1,rep,name=chatLogList,proto3" json:"chatLogList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatLogResp) Reset() {
	*x = GetChatLogResp{}
	mi := &file_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatLogResp) ProtoMessage() {}

func (x *GetChatLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatLogResp.ProtoReflect.Descriptor instead.
func (*GetChatLogResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatLogResp) GetChatLogList() []*ChatLog {
	if x != nil {
		return x.ChatLogList
	}
	return nil
}

// 5. 消息已读ack (推游标)
type AckMessageReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        string                 `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,3,opt,name=readSeq,proto3" json:"readSeq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckMessageReadReq) Reset() {
	*x = AckMessageReadReq{}
	mi := &file_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageReadReq) ProtoMessage() {}

func (x *AckMessageReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageReadReq.ProtoReflect.Descriptor instead.
func (*AckMessageReadReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{10}
}

func (x *AckMessageReadReq) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AckMessageReadReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AckMessageReadReq) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type AckMessageReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageReadResp) Reset() {
	*x = AckMessageReadResp{}
	mi := &file_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageReadResp) ProtoMessage() {}

func (x *AckMessageReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageReadResp.ProtoReflect.Descriptor instead.
func (*AckMessageReadResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{11}
}

func (x *AckMessageReadResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_im_proto protoreflect.FileDescriptor

const file_im_proto_rawDesc = "" +
	"\n" +
	"\bim.proto\x12\x02im\"f\n" +
	"\x18SetUpUserConversationReq\x12\x16\n" +
	"\x06sendId\x18\x01 \x01(\tR\x06sendId\x12\x16\n" +
	"\x06recvId\x18\x02 \x01(\tR\x06recvId\x12\x1a\n" +
	"\bchatType\x18\x03 \x01(\x05R\bchatType\"C\n" +
	"\x19SetUpUserConversationResp\x12&\n" +
	"\x0econversationId\x18\x01 \x01(\tR\x0econversationId\"\xd3\x01\n" +
	"\rPutChatLogReq\x12&\n" +
	"\x0econversationId\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06sendId\x18\x02 \x01(\tR\x06sendId\x12\x16\n" +
	"\x06recvId\x18\x03 \x01(\tR\x06recvId\x12\x1a\n" +
	"\bchatType\x18\x04 \x01(\x05R\bchatType\x12\x18\n" +
	"\amsgType\x18\x05 \x01(\x05R\amsgType\x12\x1e\n" +
	"\n" +
	"msgContent\x18\x06 \x01(\tR\n" +
	"msgContent\x12\x14\n" +
	"\x05msgId\x18\a \x01(\tR\x05msgId\"T\n" +
	"\x0ePutChatLogResp\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1a\n" +
	"\bsendTime\x18\x03 \x01(\x03R\bsendTime\"/\n" +
	"\x13GetConversationsReq\x12\x18\n" +
	"\aownerId\x18\x01 \x01(\tR\aownerId\"\xaa\x01\n" +
	"\fConversation\x12&\n" +
	"\x0econversationId\x18\x01 \x01(\tR\x0econversationId\x12\x1a\n" +
	"\bchatType\x18\x02 \x01(\x05R\bchatType\x12\x16\n" +
	"\x06maxSeq\x18\x03 \x01(\x03R\x06maxSeq\x12\x1c\n" +
	"\tlatestMsg\x18\x04 \x01(\tR\tlatestMsg\x12 \n" +
	"\vlastMsgTime\x18\x05 \x01(\x03R\vlastMsgTime\"T\n" +
	"\x14GetConversationsResp\x12<\n" +
	"\x10conversationList\x18\x01 \x03(\v2\x10.im.ConversationR\x10conversationList\"m\n" +
	"\rGetChatLogReq\x12&\n" +
	"\x0econversationId\x18\x01 \x01(\tR\x0econversationId\x12\x1e\n" +
	"\n" +
	"cursorTime\x18\x02 \x01(\x03R\n" +
	"cursorTime\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xcd\x01\n" +
	"\aChatLog\x12\x14\n" +
	"\x05msgId\x18\x01 \x01(\tR\x05msgId\x12&\n" +
	"\x0econversationId\x18\x02 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06sendId\x18\x04 \x01(\tR\x06sendId\x12\x16\n" +
	"\x06recvId\x18\x05 \x01(\tR\x06recvId\x12\x18\n" +
	"\amsgType\x18\x06 \x01(\x05R\amsgType\x12\x1e\n" +
	"\n" +
	"msgContent\x18\a \x01(\tR\n" +
	"msgContent\x12\x1a\n" +
	"\bsendTime\x18\b \x01(\x03R\bsendTime\"?\n" +
	"\x0eGetChatLogResp\x12-\n" +
	"\vchatLogList\x18\x01 \x03(\v2\v.im.ChatLogR\vchatLogList\"o\n" +
	"\x11AckMessageReadReq\x12\x18\n" +
	"\aownerId\x18\x01 \x01(\tR\aownerId\x12&\n" +
	"\x0econversationId\x18\x02 \x01(\tR\x0econversationId\x12\x18\n" +
	"\areadSeq\x18\x03 \x01(\x03R\areadSeq\".\n" +
	"\x12AckMessageReadResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcc\x02\n" +
	"\x02Im\x12T\n" +
	"\x15SetUpUserConversation\x12\x1c.im.SetUpUserConversationReq\x1a\x1d.im.SetUpUserConversationResp\x123\n" +
	"\n" +
	"PutChatLog\x12\x11.im.PutChatLogReq\x1a\x12.im.PutChatLogResp\x12E\n" +
	"\x10GetConversations\x12\x17.im.GetConversationsReq\x1a\x18.im.GetConversationsResp\x123\n" +
	"\n" +
	"GetChatLog\x12\x11.im.GetChatLogReq\x1a\x12.im.GetChatLogResp\x12?\n" +
	"\x0eAckMessageRead\x12\x15.im.AckMessageReadReq\x1a\x16.im.AckMessageReadRespB\x06Z\x04./imb\x06proto3"

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData []byte
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)))
	})
	return file_im_proto_rawDescData
}

var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_im_proto_goTypes = []any{
	(*SetUpUserConversationReq)(nil),  // 0: im.SetUpUserConversationReq
	(*SetUpUserConversationResp)(nil), // 1: im.SetUpUserConversationResp
	(*PutChatLogReq)(nil),             // 2: im.PutChatLogReq
	(*PutChatLogResp)(nil),            // 3: im.PutChatLogResp
	(*GetConversationsReq)(nil),       // 4: im.GetConversationsReq
	(*Conversation)(nil),              // 5: im.Conversation
	(*GetConversationsResp)(nil),      // 6: im.GetConversationsResp
	(*GetChatLogReq)(nil),             // 7: im.GetChatLogReq
	(*ChatLog)(nil),                   // 8: im.ChatLog
	(*GetChatLogResp)(nil),            // 9: im.GetChatLogResp
	(*AckMessageReadReq)(nil),         // 10: im.AckMessageReadReq
	(*AckMessageReadResp)(nil),        // 11: im.AckMessageReadResp
}
var file_im_proto_depIdxs = []int32{
	5,  // 0: im.GetConversationsResp.conversationList:type_name -> im.Conversation
	8,  // 1: im.GetChatLogResp.chatLogList:type_name -> im.ChatLog
	0,  // 2: im.Im.SetUpUserConversation:input_type -> im.SetUpUserConversationReq
	2,  // 3: im.Im.PutChatLog:input_type -> im.PutChatLogReq
	4,  // 4: im.Im.GetConversations:input_type -> im.GetConversationsReq
	7,  // 5: im.Im.GetChatLog:input_type -> im.GetChatLogReq
	10, // 6: im.Im.AckMessageRead:input_type -> im.AckMessageReadReq
	1,  // 7: im.Im.SetUpUserConversation:output_type -> im.SetUpUserConversationResp
	3,  // 8: im.Im.PutChatLog:output_type -> im.PutChatLogResp
	6,  // 9: im.Im.GetConversations:output_type -> im.GetConversationsResp
	9,  // 10: im.Im.GetChatLog:output_type -> im.GetChatLogResp
	11, // 11: im.Im.AckMessageRead:output_type -> im.AckMessageReadResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
