// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: post.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Visibility    int32                  `protobuf:"varint,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	RelatedGameId int64                  `protobuf:"varint,6,opt,name=related_game_id,json=relatedGameId,proto3" json:"related_game_id,omitempty"`
	LikeCount     int32                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CollectCount  int32                  `protobuf:"varint,9,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PostInfo) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *PostInfo) GetRelatedGameId() int64 {
	if x != nil {
		return x.RelatedGameId
	}
	return 0
}

func (x *PostInfo) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostInfo) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostInfo) GetCollectCount() int32 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *PostInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CommentPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     int32                  `protobuf:"varint,4,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentPreview) Reset() {
	*x = CommentPreview{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentPreview) ProtoMessage() {}

func (x *CommentPreview) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentPreview.ProtoReflect.Descriptor instead.
func (*CommentPreview) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *CommentPreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentPreview) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentPreview) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentPreview) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentPreview) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PostDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostInfo              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	TopComments   []*CommentPreview      `protobuf:"bytes,2,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetail) Reset() {
	*x = PostDetail{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetail) ProtoMessage() {}

func (x *PostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetail.ProtoReflect.Descriptor instead.
func (*PostDetail) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostDetail) GetPost() *PostInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostDetail) GetTopComments() []*CommentPreview {
	if x != nil {
		return x.TopComments
	}
	return nil
}

type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Visibility    int32                  `protobuf:"varint,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	RelatedGameId int64                  `protobuf:"varint,5,opt,name=related_game_id,json=relatedGameId,proto3" json:"related_game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostReq) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreatePostReq) GetVisibility() int32 {
	if x != nil {
		return x.Visibility
	}
	return 0
}

func (x *CreatePostReq) GetRelatedGameId() int64 {
	if x != nil {
		return x.RelatedGameId
	}
	return 0
}

type CreatePostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResp) Reset() {
	*x = CreatePostResp{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResp) ProtoMessage() {}

func (x *CreatePostResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResp.ProtoReflect.Descriptor instead.
func (*CreatePostResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostResp) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetFriendTimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // e.g., timestamp score from redis zset
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendTimelineReq) Reset() {
	*x = GetFriendTimelineReq{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendTimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendTimelineReq) ProtoMessage() {}

func (x *GetFriendTimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendTimelineReq.ProtoReflect.Descriptor instead.
func (*GetFriendTimelineReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *GetFriendTimelineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFriendTimelineReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetFriendTimelineReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFriendTimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PostDetail          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendTimelineResp) Reset() {
	*x = GetFriendTimelineResp{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendTimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendTimelineResp) ProtoMessage() {}

func (x *GetFriendTimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendTimelineResp.ProtoReflect.Descriptor instead.
func (*GetFriendTimelineResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *GetFriendTimelineResp) GetList() []*PostDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type GetPublicTimelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // e.g., max auto-increment id or timestamp
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTimelineReq) Reset() {
	*x = GetPublicTimelineReq{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTimelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTimelineReq) ProtoMessage() {}

func (x *GetPublicTimelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTimelineReq.ProtoReflect.Descriptor instead.
func (*GetPublicTimelineReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *GetPublicTimelineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPublicTimelineReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetPublicTimelineReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPublicTimelineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PostDetail          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicTimelineResp) Reset() {
	*x = GetPublicTimelineResp{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicTimelineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicTimelineResp) ProtoMessage() {}

func (x *GetPublicTimelineResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicTimelineResp.ProtoReflect.Descriptor instead.
func (*GetPublicTimelineResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublicTimelineResp) GetList() []*PostDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type InteractReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 1: Post, 2: Comment
	Action        int32                  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`                           // 1: Like, 2: Unlike, 3: Collect, 4: Uncollect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractReq) Reset() {
	*x = InteractReq{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractReq) ProtoMessage() {}

func (x *InteractReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractReq.ProtoReflect.Descriptor instead.
func (*InteractReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *InteractReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InteractReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *InteractReq) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *InteractReq) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type InteractResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractResp) Reset() {
	*x = InteractResp{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractResp) ProtoMessage() {}

func (x *InteractResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractResp.ProtoReflect.Descriptor instead.
func (*InteractResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *InteractResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RootId        int64                  `protobuf:"varint,5,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCommentResp) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetPostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailReq) Reset() {
	*x = GetPostDetailReq{}
	mi := &file_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailReq) ProtoMessage() {}

func (x *GetPostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailReq.ProtoReflect.Descriptor instead.
func (*GetPostDetailReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostDetailReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *PostDetail            `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostDetailResp) Reset() {
	*x = GetPostDetailResp{}
	mi := &file_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostDetailResp) ProtoMessage() {}

func (x *GetPostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostDetailResp.ProtoReflect.Descriptor instead.
func (*GetPostDetailResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostDetailResp) GetDetail() *PostDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\"\xb5\x02\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x05R\n" +
	"visibility\x12&\n" +
	"\x0frelated_game_id\x18\x06 \x01(\x03R\rrelatedGameId\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\b \x01(\x05R\fcommentCount\x12#\n" +
	"\rcollect_count\x18\t \x01(\x05R\fcollectCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\x91\x01\n" +
	"\x0eCommentPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\x04 \x01(\x05R\tlikeCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"i\n" +
	"\n" +
	"PostDetail\x12\"\n" +
	"\x04post\x18\x01 \x01(\v2\x0e.post.PostInfoR\x04post\x127\n" +
	"\ftop_comments\x18\x02 \x03(\v2\x14.post.CommentPreviewR\vtopComments\"\xa2\x01\n" +
	"\rCreatePostReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x05R\n" +
	"visibility\x12&\n" +
	"\x0frelated_game_id\x18\x05 \x01(\x03R\rrelatedGameId\")\n" +
	"\x0eCreatePostResp\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"]\n" +
	"\x14GetFriendTimelineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"=\n" +
	"\x15GetFriendTimelineResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.post.PostDetailR\x04list\"]\n" +
	"\x14GetPublicTimelineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"=\n" +
	"\x15GetPublicTimelineResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.post.PostDetailR\x04list\"|\n" +
	"\vInteractReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\x05R\n" +
	"targetType\x12\x16\n" +
	"\x06action\x18\x04 \x01(\x05R\x06action\"(\n" +
	"\fInteractResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x94\x01\n" +
	"\x10CreateCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x17\n" +
	"\aroot_id\x18\x05 \x01(\x03R\x06rootId\"2\n" +
	"\x11CreateCommentResp\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\"+\n" +
	"\x10GetPostDetailReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"=\n" +
	"\x11GetPostDetailResp\x12(\n" +
	"\x06detail\x18\x01 \x01(\v2\x10.post.PostDetailR\x06detail2\x99\x03\n" +
	"\vPostService\x127\n" +
	"\n" +
	"CreatePost\x12\x13.post.CreatePostReq\x1a\x14.post.CreatePostResp\x12L\n" +
	"\x11GetFriendTimeline\x12\x1a.post.GetFriendTimelineReq\x1a\x1b.post.GetFriendTimelineResp\x12L\n" +
	"\x11GetPublicTimeline\x12\x1a.post.GetPublicTimelineReq\x1a\x1b.post.GetPublicTimelineResp\x121\n" +
	"\bInteract\x12\x11.post.InteractReq\x1a\x12.post.InteractResp\x12@\n" +
	"\rCreateComment\x12\x16.post.CreateCommentReq\x1a\x17.post.CreateCommentResp\x12@\n" +
	"\rGetPostDetail\x12\x16.post.GetPostDetailReq\x1a\x17.post.GetPostDetailRespB\bZ\x06./postb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_post_proto_goTypes = []any{
	(*PostInfo)(nil),              // 0: post.PostInfo
	(*CommentPreview)(nil),        // 1: post.CommentPreview
	(*PostDetail)(nil),            // 2: post.PostDetail
	(*CreatePostReq)(nil),         // 3: post.CreatePostReq
	(*CreatePostResp)(nil),        // 4: post.CreatePostResp
	(*GetFriendTimelineReq)(nil),  // 5: post.GetFriendTimelineReq
	(*GetFriendTimelineResp)(nil), // 6: post.GetFriendTimelineResp
	(*GetPublicTimelineReq)(nil),  // 7: post.GetPublicTimelineReq
	(*GetPublicTimelineResp)(nil), // 8: post.GetPublicTimelineResp
	(*InteractReq)(nil),           // 9: post.InteractReq
	(*InteractResp)(nil),          // 10: post.InteractResp
	(*CreateCommentReq)(nil),      // 11: post.CreateCommentReq
	(*CreateCommentResp)(nil),     // 12: post.CreateCommentResp
	(*GetPostDetailReq)(nil),      // 13: post.GetPostDetailReq
	(*GetPostDetailResp)(nil),     // 14: post.GetPostDetailResp
}
var file_post_proto_depIdxs = []int32{
	0,  // 0: post.PostDetail.post:type_name -> post.PostInfo
	1,  // 1: post.PostDetail.top_comments:type_name -> post.CommentPreview
	2,  // 2: post.GetFriendTimelineResp.list:type_name -> post.PostDetail
	2,  // 3: post.GetPublicTimelineResp.list:type_name -> post.PostDetail
	2,  // 4: post.GetPostDetailResp.detail:type_name -> post.PostDetail
	3,  // 5: post.PostService.CreatePost:input_type -> post.CreatePostReq
	5,  // 6: post.PostService.GetFriendTimeline:input_type -> post.GetFriendTimelineReq
	7,  // 7: post.PostService.GetPublicTimeline:input_type -> post.GetPublicTimelineReq
	9,  // 8: post.PostService.Interact:input_type -> post.InteractReq
	11, // 9: post.PostService.CreateComment:input_type -> post.CreateCommentReq
	13, // 10: post.PostService.GetPostDetail:input_type -> post.GetPostDetailReq
	4,  // 11: post.PostService.CreatePost:output_type -> post.CreatePostResp
	6,  // 12: post.PostService.GetFriendTimeline:output_type -> post.GetFriendTimelineResp
	8,  // 13: post.PostService.GetPublicTimeline:output_type -> post.GetPublicTimelineResp
	10, // 14: post.PostService.Interact:output_type -> post.InteractResp
	12, // 15: post.PostService.CreateComment:output_type -> post.CreateCommentResp
	14, // 16: post.PostService.GetPostDetail:output_type -> post.GetPostDetailResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
