// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: game.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_GetGameDetail_FullMethodName    = "/game.Game/GetGameDetail"
	Game_FilterGames_FullMethodName      = "/game.Game/FilterGames"
	Game_SearchGames_FullMethodName      = "/game.Game/SearchGames"
	Game_GetGameBasicInfo_FullMethodName = "/game.Game/GetGameBasicInfo"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Endpoint
type GameClient interface {
	// 获取桌游详细信息
	GetGameDetail(ctx context.Context, in *GetGameDetailReq, opts ...grpc.CallOption) (*GetGameDetailResp, error)
	// 高级组合筛选 (核心亮点)
	FilterGames(ctx context.Context, in *FilterGamesReq, opts ...grpc.CallOption) (*FilterGamesResp, error)
	// 模糊搜索
	SearchGames(ctx context.Context, in *SearchGamesReq, opts ...grpc.CallOption) (*SearchGamesResp, error)
	// 批量拉取桌游轻量摘要
	GetGameBasicInfo(ctx context.Context, in *GetGameBasicInfoReq, opts ...grpc.CallOption) (*GetGameBasicInfoResp, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) GetGameDetail(ctx context.Context, in *GetGameDetailReq, opts ...grpc.CallOption) (*GetGameDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameDetailResp)
	err := c.cc.Invoke(ctx, Game_GetGameDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) FilterGames(ctx context.Context, in *FilterGamesReq, opts ...grpc.CallOption) (*FilterGamesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterGamesResp)
	err := c.cc.Invoke(ctx, Game_FilterGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) SearchGames(ctx context.Context, in *SearchGamesReq, opts ...grpc.CallOption) (*SearchGamesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGamesResp)
	err := c.cc.Invoke(ctx, Game_SearchGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetGameBasicInfo(ctx context.Context, in *GetGameBasicInfoReq, opts ...grpc.CallOption) (*GetGameBasicInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameBasicInfoResp)
	err := c.cc.Invoke(ctx, Game_GetGameBasicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
//
// Service Endpoint
type GameServer interface {
	// 获取桌游详细信息
	GetGameDetail(context.Context, *GetGameDetailReq) (*GetGameDetailResp, error)
	// 高级组合筛选 (核心亮点)
	FilterGames(context.Context, *FilterGamesReq) (*FilterGamesResp, error)
	// 模糊搜索
	SearchGames(context.Context, *SearchGamesReq) (*SearchGamesResp, error)
	// 批量拉取桌游轻量摘要
	GetGameBasicInfo(context.Context, *GetGameBasicInfoReq) (*GetGameBasicInfoResp, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) GetGameDetail(context.Context, *GetGameDetailReq) (*GetGameDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameDetail not implemented")
}
func (UnimplementedGameServer) FilterGames(context.Context, *FilterGamesReq) (*FilterGamesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterGames not implemented")
}
func (UnimplementedGameServer) SearchGames(context.Context, *SearchGamesReq) (*SearchGamesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGames not implemented")
}
func (UnimplementedGameServer) GetGameBasicInfo(context.Context, *GetGameBasicInfoReq) (*GetGameBasicInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameBasicInfo not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call pancis, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_GetGameDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetGameDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GetGameDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetGameDetail(ctx, req.(*GetGameDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_FilterGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterGamesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).FilterGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_FilterGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).FilterGames(ctx, req.(*FilterGamesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_SearchGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGamesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).SearchGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_SearchGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).SearchGames(ctx, req.(*SearchGamesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetGameBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetGameBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GetGameBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetGameBasicInfo(ctx, req.(*GetGameBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameDetail",
			Handler:    _Game_GetGameDetail_Handler,
		},
		{
			MethodName: "FilterGames",
			Handler:    _Game_FilterGames_Handler,
		},
		{
			MethodName: "SearchGames",
			Handler:    _Game_SearchGames_Handler,
		},
		{
			MethodName: "GetGameBasicInfo",
			Handler:    _Game_GetGameBasicInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
