// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Category         string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Theme            string                 `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	Mechanic         string                 `protobuf:"bytes,4,opt,name=mechanic,proto3" json:"mechanic,omitempty"`
	Portability      string                 `protobuf:"bytes,5,opt,name=portability,proto3" json:"portability,omitempty"`
	TableRequirement string                 `protobuf:"bytes,6,opt,name=table_requirement,json=tableRequirement,proto3" json:"table_requirement,omitempty"`
	SuitableAge      int32                  `protobuf:"varint,7,opt,name=suitable_age,json=suitableAge,proto3" json:"suitable_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CategoryInfo) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *CategoryInfo) GetMechanic() string {
	if x != nil {
		return x.Mechanic
	}
	return ""
}

func (x *CategoryInfo) GetPortability() string {
	if x != nil {
		return x.Portability
	}
	return ""
}

func (x *CategoryInfo) GetTableRequirement() string {
	if x != nil {
		return x.TableRequirement
	}
	return ""
}

func (x *CategoryInfo) GetSuitableAge() int32 {
	if x != nil {
		return x.SuitableAge
	}
	return 0
}

type GameDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameDetailReq) Reset() {
	*x = GameDetailReq{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDetailReq) ProtoMessage() {}

func (x *GameDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDetailReq.ProtoReflect.Descriptor instead.
func (*GameDetailReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameDetailReq) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GameDetailResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn                string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	CoverImg              string                 `protobuf:"bytes,4,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Score                 float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	ScoreCount            int32                  `protobuf:"varint,6,opt,name=score_count,json=scoreCount,proto3" json:"score_count,omitempty"`
	MinPlayers            int32                  `protobuf:"varint,7,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers            int32                  `protobuf:"varint,8,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	MinRecommendedPlayers int32                  `protobuf:"varint,9,opt,name=min_recommended_players,json=minRecommendedPlayers,proto3" json:"min_recommended_players,omitempty"`
	MaxRecommendedPlayers int32                  `protobuf:"varint,10,opt,name=max_recommended_players,json=maxRecommendedPlayers,proto3" json:"max_recommended_players,omitempty"`
	NeedHost              int32                  `protobuf:"varint,11,opt,name=need_host,json=needHost,proto3" json:"need_host,omitempty"`
	RankPosition          int32                  `protobuf:"varint,12,opt,name=rank_position,json=rankPosition,proto3" json:"rank_position,omitempty"`
	Year                  int32                  `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Description           string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty            float64                `protobuf:"fixed64,15,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	DurationPerPlayer     int32                  `protobuf:"varint,16,opt,name=duration_per_player,json=durationPerPlayer,proto3" json:"duration_per_player,omitempty"`
	SetupTime             string                 `protobuf:"bytes,17,opt,name=setup_time,json=setupTime,proto3" json:"setup_time,omitempty"`
	LanguageDependency    string                 `protobuf:"bytes,18,opt,name=language_dependency,json=languageDependency,proto3" json:"language_dependency,omitempty"`
	CategoryInfo          *CategoryInfo          `protobuf:"bytes,19,opt,name=category_info,json=categoryInfo,proto3" json:"category_info,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GameDetailResp) Reset() {
	*x = GameDetailResp{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDetailResp) ProtoMessage() {}

func (x *GameDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDetailResp.ProtoReflect.Descriptor instead.
func (*GameDetailResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameDetailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameDetailResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameDetailResp) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *GameDetailResp) GetCoverImg() string {
	if x != nil {
		return x.CoverImg
	}
	return ""
}

func (x *GameDetailResp) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameDetailResp) GetScoreCount() int32 {
	if x != nil {
		return x.ScoreCount
	}
	return 0
}

func (x *GameDetailResp) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *GameDetailResp) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameDetailResp) GetMinRecommendedPlayers() int32 {
	if x != nil {
		return x.MinRecommendedPlayers
	}
	return 0
}

func (x *GameDetailResp) GetMaxRecommendedPlayers() int32 {
	if x != nil {
		return x.MaxRecommendedPlayers
	}
	return 0
}

func (x *GameDetailResp) GetNeedHost() int32 {
	if x != nil {
		return x.NeedHost
	}
	return 0
}

func (x *GameDetailResp) GetRankPosition() int32 {
	if x != nil {
		return x.RankPosition
	}
	return 0
}

func (x *GameDetailResp) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GameDetailResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GameDetailResp) GetDifficulty() float64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GameDetailResp) GetDurationPerPlayer() int32 {
	if x != nil {
		return x.DurationPerPlayer
	}
	return 0
}

func (x *GameDetailResp) GetSetupTime() string {
	if x != nil {
		return x.SetupTime
	}
	return ""
}

func (x *GameDetailResp) GetLanguageDependency() string {
	if x != nil {
		return x.LanguageDependency
	}
	return ""
}

func (x *GameDetailResp) GetCategoryInfo() *CategoryInfo {
	if x != nil {
		return x.CategoryInfo
	}
	return nil
}

type ListGamesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesReq) Reset() {
	*x = ListGamesReq{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesReq) ProtoMessage() {}

func (x *ListGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesReq.ProtoReflect.Descriptor instead.
func (*ListGamesReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *ListGamesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGamesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListGamesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListGamesReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GameItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	CoverImg      string                 `protobuf:"bytes,4,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	ScoreCount    int32                  `protobuf:"varint,6,opt,name=score_count,json=scoreCount,proto3" json:"score_count,omitempty"`
	MinPlayers    int32                  `protobuf:"varint,7,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,8,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Category      string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameItem) Reset() {
	*x = GameItem{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameItem) ProtoMessage() {}

func (x *GameItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameItem.ProtoReflect.Descriptor instead.
func (*GameItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameItem) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *GameItem) GetCoverImg() string {
	if x != nil {
		return x.CoverImg
	}
	return ""
}

func (x *GameItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameItem) GetScoreCount() int32 {
	if x != nil {
		return x.ScoreCount
	}
	return 0
}

func (x *GameItem) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *GameItem) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListGamesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*GameItem            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResp) Reset() {
	*x = ListGamesResp{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResp) ProtoMessage() {}

func (x *ListGamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResp.ProtoReflect.Descriptor instead.
func (*ListGamesResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *ListGamesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGamesResp) GetList() []*GameItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GameBasicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBasicInfoReq) Reset() {
	*x = GameBasicInfoReq{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBasicInfoReq) ProtoMessage() {}

func (x *GameBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBasicInfoReq.ProtoReflect.Descriptor instead.
func (*GameBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameBasicInfoReq) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GameBasicInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverImg      string                 `protobuf:"bytes,3,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBasicInfoResp) Reset() {
	*x = GameBasicInfoResp{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBasicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBasicInfoResp) ProtoMessage() {}

func (x *GameBasicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBasicInfoResp.ProtoReflect.Descriptor instead.
func (*GameBasicInfoResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameBasicInfoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameBasicInfoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameBasicInfoResp) GetCoverImg() string {
	if x != nil {
		return x.CoverImg
	}
	return ""
}

func (x *GameBasicInfoResp) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\xe2\x01\n" +
	"\fCategoryInfo\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x14\n" +
	"\x05theme\x18\x03 \x01(\tR\x05theme\x12\x1a\n" +
	"\bmechanic\x18\x04 \x01(\tR\bmechanic\x12 \n" +
	"\vportability\x18\x05 \x01(\tR\vportability\x12+\n" +
	"\x11table_requirement\x18\x06 \x01(\tR\x10tableRequirement\x12!\n" +
	"\fsuitable_age\x18\a \x01(\x05R\vsuitableAge\"(\n" +
	"\rGameDetailReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"\xa4\x05\n" +
	"\x0eGameDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x1b\n" +
	"\tcover_img\x18\x04 \x01(\tR\bcoverImg\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1f\n" +
	"\vscore_count\x18\x06 \x01(\x05R\n" +
	"scoreCount\x12\x1f\n" +
	"\vmin_players\x18\a \x01(\x05R\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\b \x01(\x05R\n" +
	"maxPlayers\x126\n" +
	"\x17min_recommended_players\x18\t \x01(\x05R\x15minRecommendedPlayers\x126\n" +
	"\x17max_recommended_players\x18\n" +
	" \x01(\x05R\x15maxRecommendedPlayers\x12\x1b\n" +
	"\tneed_host\x18\v \x01(\x05R\bneedHost\x12#\n" +
	"\rrank_position\x18\f \x01(\x05R\frankPosition\x12\x12\n" +
	"\x04year\x18\r \x01(\x05R\x04year\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x0f \x01(\x01R\n" +
	"difficulty\x12.\n" +
	"\x13duration_per_player\x18\x10 \x01(\x05R\x11durationPerPlayer\x12\x1d\n" +
	"\n" +
	"setup_time\x18\x11 \x01(\tR\tsetupTime\x12/\n" +
	"\x13language_dependency\x18\x12 \x01(\tR\x12languageDependency\x127\n" +
	"\rcategory_info\x18\x13 \x01(\v2\x12.game.CategoryInfoR\fcategoryInfo\"l\n" +
	"\fListGamesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xf9\x01\n" +
	"\bGameItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x1b\n" +
	"\tcover_img\x18\x04 \x01(\tR\bcoverImg\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1f\n" +
	"\vscore_count\x18\x06 \x01(\x05R\n" +
	"scoreCount\x12\x1f\n" +
	"\vmin_players\x18\a \x01(\x05R\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\b \x01(\x05R\n" +
	"maxPlayers\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\"I\n" +
	"\rListGamesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\"\n" +
	"\x04list\x18\x02 \x03(\v2\x0e.game.GameItemR\x04list\"+\n" +
	"\x10GameBasicInfoReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"j\n" +
	"\x11GameBasicInfoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_img\x18\x03 \x01(\tR\bcoverImg\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score2\xbd\x01\n" +
	"\x04Game\x12:\n" +
	"\rGetGameDetail\x12\x13.game.GameDetailReq\x1a\x14.game.GameDetailResp\x124\n" +
	"\tListGames\x12\x12.game.ListGamesReq\x1a\x13.game.ListGamesResp\x12C\n" +
	"\x10GetGameBasicInfo\x12\x16.game.GameBasicInfoReq\x1a\x17.game.GameBasicInfoRespB\bZ\x06./gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_proto_goTypes = []any{
	(*CategoryInfo)(nil),      // 0: game.CategoryInfo
	(*GameDetailReq)(nil),     // 1: game.GameDetailReq
	(*GameDetailResp)(nil),    // 2: game.GameDetailResp
	(*ListGamesReq)(nil),      // 3: game.ListGamesReq
	(*GameItem)(nil),          // 4: game.GameItem
	(*ListGamesResp)(nil),     // 5: game.ListGamesResp
	(*GameBasicInfoReq)(nil),  // 6: game.GameBasicInfoReq
	(*GameBasicInfoResp)(nil), // 7: game.GameBasicInfoResp
}
var file_game_proto_depIdxs = []int32{
	0, // 0: game.GameDetailResp.category_info:type_name -> game.CategoryInfo
	4, // 1: game.ListGamesResp.list:type_name -> game.GameItem
	1, // 2: game.Game.GetGameDetail:input_type -> game.GameDetailReq
	3, // 3: game.Game.ListGames:input_type -> game.ListGamesReq
	6, // 4: game.Game.GetGameBasicInfo:input_type -> game.GameBasicInfoReq
	2, // 5: game.Game.GetGameDetail:output_type -> game.GameDetailResp
	5, // 6: game.Game.ListGames:output_type -> game.ListGamesResp
	7, // 7: game.Game.GetGameBasicInfo:output_type -> game.GameBasicInfoResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
