// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Models
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      int32                  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

type GameResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResource) Reset() {
	*x = GameResource{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResource) ProtoMessage() {}

func (x *GameResource) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResource.ProtoReflect.Descriptor instead.
func (*GameResource) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameResource) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameResource) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GameResource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GameResource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GameBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverImg      string                 `protobuf:"bytes,3,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBasic) Reset() {
	*x = GameBasic{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBasic) ProtoMessage() {}

func (x *GameBasic) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBasic.ProtoReflect.Descriptor instead.
func (*GameBasic) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameBasic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameBasic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameBasic) GetCoverImg() string {
	if x != nil {
		return x.CoverImg
	}
	return ""
}

func (x *GameBasic) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 2.1 GetGameDetail
type GetGameDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameDetailReq) Reset() {
	*x = GetGameDetailReq{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameDetailReq) ProtoMessage() {}

func (x *GetGameDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameDetailReq.ProtoReflect.Descriptor instead.
func (*GetGameDetailReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameDetailReq) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetGameDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	CoverImg      string                 `protobuf:"bytes,4,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	ScoreCount    int32                  `protobuf:"varint,6,opt,name=score_count,json=scoreCount,proto3" json:"score_count,omitempty"`
	PublishYear   int32                  `protobuf:"varint,7,opt,name=publish_year,json=publishYear,proto3" json:"publish_year,omitempty"`
	MinPlayers    int32                  `protobuf:"varint,8,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,9,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	DurationMin   int32                  `protobuf:"varint,10,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	DurationMax   int32                  `protobuf:"varint,11,opt,name=duration_max,json=durationMax,proto3" json:"duration_max,omitempty"`
	Complexity    float64                `protobuf:"fixed64,12,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`           // 关联的标签
	Resources     []*GameResource        `protobuf:"bytes,15,rep,name=resources,proto3" json:"resources,omitempty"` // 关联的资源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameDetailResp) Reset() {
	*x = GetGameDetailResp{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameDetailResp) ProtoMessage() {}

func (x *GetGameDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameDetailResp.ProtoReflect.Descriptor instead.
func (*GetGameDetailResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameDetailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGameDetailResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGameDetailResp) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *GetGameDetailResp) GetCoverImg() string {
	if x != nil {
		return x.CoverImg
	}
	return ""
}

func (x *GetGameDetailResp) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetGameDetailResp) GetScoreCount() int32 {
	if x != nil {
		return x.ScoreCount
	}
	return 0
}

func (x *GetGameDetailResp) GetPublishYear() int32 {
	if x != nil {
		return x.PublishYear
	}
	return 0
}

func (x *GetGameDetailResp) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *GetGameDetailResp) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GetGameDetailResp) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *GetGameDetailResp) GetDurationMax() int32 {
	if x != nil {
		return x.DurationMax
	}
	return 0
}

func (x *GetGameDetailResp) GetComplexity() float64 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

func (x *GetGameDetailResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetGameDetailResp) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetGameDetailResp) GetResources() []*GameResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// 2.2 FilterGames
type FilterGamesReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerCount     int32                  `protobuf:"varint,1,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`            // e.g., 4
	DurationRange   string                 `protobuf:"bytes,2,opt,name=duration_range,json=durationRange,proto3" json:"duration_range,omitempty"`       // "SHORT", "MEDIUM", "LONG"
	ComplexityLevel string                 `protobuf:"bytes,3,opt,name=complexity_level,json=complexityLevel,proto3" json:"complexity_level,omitempty"` // "LIGHT", "MEDIUM", "HEAVY"
	TagIds          []int64                `protobuf:"varint,4,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`                    // 需要满足的 Tag ID 列表
	Page            int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Size            int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	SortBy          string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // "score", "hot"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterGamesReq) Reset() {
	*x = FilterGamesReq{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterGamesReq) ProtoMessage() {}

func (x *FilterGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterGamesReq.ProtoReflect.Descriptor instead.
func (*FilterGamesReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *FilterGamesReq) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *FilterGamesReq) GetDurationRange() string {
	if x != nil {
		return x.DurationRange
	}
	return ""
}

func (x *FilterGamesReq) GetComplexityLevel() string {
	if x != nil {
		return x.ComplexityLevel
	}
	return ""
}

func (x *FilterGamesReq) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *FilterGamesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FilterGamesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FilterGamesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type FilterGamesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	GameIds       []int64                `protobuf:"varint,2,rep,packed,name=game_ids,json=gameIds,proto3" json:"game_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterGamesResp) Reset() {
	*x = FilterGamesResp{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterGamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterGamesResp) ProtoMessage() {}

func (x *FilterGamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterGamesResp.ProtoReflect.Descriptor instead.
func (*FilterGamesResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *FilterGamesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FilterGamesResp) GetGameIds() []int64 {
	if x != nil {
		return x.GameIds
	}
	return nil
}

// 2.3 SearchGames
type SearchGamesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGamesReq) Reset() {
	*x = SearchGamesReq{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGamesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGamesReq) ProtoMessage() {}

func (x *SearchGamesReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGamesReq.ProtoReflect.Descriptor instead.
func (*SearchGamesReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *SearchGamesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchGamesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchGamesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchGamesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*GameBasic           `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGamesResp) Reset() {
	*x = SearchGamesResp{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGamesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGamesResp) ProtoMessage() {}

func (x *SearchGamesResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGamesResp.ProtoReflect.Descriptor instead.
func (*SearchGamesResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *SearchGamesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchGamesResp) GetList() []*GameBasic {
	if x != nil {
		return x.List
	}
	return nil
}

// 2.4 GetGameBasicInfo
type GetGameBasicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameIds       []int64                `protobuf:"varint,1,rep,packed,name=game_ids,json=gameIds,proto3" json:"game_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBasicInfoReq) Reset() {
	*x = GetGameBasicInfoReq{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBasicInfoReq) ProtoMessage() {}

func (x *GetGameBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBasicInfoReq.ProtoReflect.Descriptor instead.
func (*GetGameBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameBasicInfoReq) GetGameIds() []int64 {
	if x != nil {
		return x.GameIds
	}
	return nil
}

type GetGameBasicInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameBasics    map[int64]*GameBasic   `protobuf:"bytes,1,rep,name=game_basics,json=gameBasics,proto3" json:"game_basics,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBasicInfoResp) Reset() {
	*x = GetGameBasicInfoResp{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBasicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBasicInfoResp) ProtoMessage() {}

func (x *GetGameBasicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBasicInfoResp.ProtoReflect.Descriptor instead.
func (*GetGameBasicInfoResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameBasicInfoResp) GetGameBasics() map[int64]*GameBasic {
	if x != nil {
		return x.GameBasics
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"E\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\x05R\bcategory\"Z\n" +
	"\fGameResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"b\n" +
	"\tGameBasic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_img\x18\x03 \x01(\tR\bcoverImg\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"+\n" +
	"\x10GetGameDetailReq\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"\xe2\x03\n" +
	"\x11GetGameDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x1b\n" +
	"\tcover_img\x18\x04 \x01(\tR\bcoverImg\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1f\n" +
	"\vscore_count\x18\x06 \x01(\x05R\n" +
	"scoreCount\x12!\n" +
	"\fpublish_year\x18\a \x01(\x05R\vpublishYear\x12\x1f\n" +
	"\vmin_players\x18\b \x01(\x05R\n" +
	"minPlayers\x12\x1f\n" +
	"\vmax_players\x18\t \x01(\x05R\n" +
	"maxPlayers\x12!\n" +
	"\fduration_min\x18\n" +
	" \x01(\x05R\vdurationMin\x12!\n" +
	"\fduration_max\x18\v \x01(\x05R\vdurationMax\x12\x1e\n" +
	"\n" +
	"complexity\x18\f \x01(\x01R\n" +
	"complexity\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x1d\n" +
	"\x04tags\x18\x0e \x03(\v2\t.game.TagR\x04tags\x120\n" +
	"\tresources\x18\x0f \x03(\v2\x12.game.GameResourceR\tresources\"\xdf\x01\n" +
	"\x0eFilterGamesReq\x12!\n" +
	"\fplayer_count\x18\x01 \x01(\x05R\vplayerCount\x12%\n" +
	"\x0eduration_range\x18\x02 \x01(\tR\rdurationRange\x12)\n" +
	"\x10complexity_level\x18\x03 \x01(\tR\x0fcomplexityLevel\x12\x17\n" +
	"\atag_ids\x18\x04 \x03(\x03R\x06tagIds\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\"B\n" +
	"\x0fFilterGamesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x19\n" +
	"\bgame_ids\x18\x02 \x03(\x03R\agameIds\"R\n" +
	"\x0eSearchGamesReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"L\n" +
	"\x0fSearchGamesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12#\n" +
	"\x04list\x18\x02 \x03(\v2\x0f.game.GameBasicR\x04list\"0\n" +
	"\x13GetGameBasicInfoReq\x12\x19\n" +
	"\bgame_ids\x18\x01 \x03(\x03R\agameIds\"\xb3\x01\n" +
	"\x14GetGameBasicInfoResp\x12K\n" +
	"\vgame_basics\x18\x01 \x03(\v2*.game.GetGameBasicInfoResp.GameBasicsEntryR\n" +
	"gameBasics\x1aN\n" +
	"\x0fGameBasicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.game.GameBasicR\x05value:\x028\x012\x8b\x02\n" +
	"\x04Game\x12@\n" +
	"\rGetGameDetail\x12\x16.game.GetGameDetailReq\x1a\x17.game.GetGameDetailResp\x12:\n" +
	"\vFilterGames\x12\x14.game.FilterGamesReq\x1a\x15.game.FilterGamesResp\x12:\n" +
	"\vSearchGames\x12\x14.game.SearchGamesReq\x1a\x15.game.SearchGamesResp\x12I\n" +
	"\x10GetGameBasicInfo\x12\x19.game.GetGameBasicInfoReq\x1a\x1a.game.GetGameBasicInfoRespB\bZ\x06./gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_game_proto_goTypes = []any{
	(*Tag)(nil),                  // 0: game.Tag
	(*GameResource)(nil),         // 1: game.GameResource
	(*GameBasic)(nil),            // 2: game.GameBasic
	(*GetGameDetailReq)(nil),     // 3: game.GetGameDetailReq
	(*GetGameDetailResp)(nil),    // 4: game.GetGameDetailResp
	(*FilterGamesReq)(nil),       // 5: game.FilterGamesReq
	(*FilterGamesResp)(nil),      // 6: game.FilterGamesResp
	(*SearchGamesReq)(nil),       // 7: game.SearchGamesReq
	(*SearchGamesResp)(nil),      // 8: game.SearchGamesResp
	(*GetGameBasicInfoReq)(nil),  // 9: game.GetGameBasicInfoReq
	(*GetGameBasicInfoResp)(nil), // 10: game.GetGameBasicInfoResp
	nil,                          // 11: game.GetGameBasicInfoResp.GameBasicsEntry
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: game.GetGameDetailResp.tags:type_name -> game.Tag
	1,  // 1: game.GetGameDetailResp.resources:type_name -> game.GameResource
	2,  // 2: game.SearchGamesResp.list:type_name -> game.GameBasic
	11, // 3: game.GetGameBasicInfoResp.game_basics:type_name -> game.GetGameBasicInfoResp.GameBasicsEntry
	2,  // 4: game.GetGameBasicInfoResp.GameBasicsEntry.value:type_name -> game.GameBasic
	3,  // 5: game.Game.GetGameDetail:input_type -> game.GetGameDetailReq
	5,  // 6: game.Game.FilterGames:input_type -> game.FilterGamesReq
	7,  // 7: game.Game.SearchGames:input_type -> game.SearchGamesReq
	9,  // 8: game.Game.GetGameBasicInfo:input_type -> game.GetGameBasicInfoReq
	4,  // 9: game.Game.GetGameDetail:output_type -> game.GetGameDetailResp
	6,  // 10: game.Game.FilterGames:output_type -> game.FilterGamesResp
	8,  // 11: game.Game.SearchGames:output_type -> game.SearchGamesResp
	10, // 12: game.Game.GetGameBasicInfo:output_type -> game.GetGameBasicInfoResp
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
