// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: game.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_GetGameDetail_FullMethodName    = "/game.Game/GetGameDetail"
	Game_ListGames_FullMethodName        = "/game.Game/ListGames"
	Game_GetGameBasicInfo_FullMethodName = "/game.Game/GetGameBasicInfo"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameClient interface {
	// 获取桌游详细信息
	GetGameDetail(ctx context.Context, in *GameDetailReq, opts ...grpc.CallOption) (*GameDetailResp, error)
	// 分页查询桌游列表
	ListGames(ctx context.Context, in *ListGamesReq, opts ...grpc.CallOption) (*ListGamesResp, error)
	// 获取桌游基础摘要
	GetGameBasicInfo(ctx context.Context, in *GameBasicInfoReq, opts ...grpc.CallOption) (*GameBasicInfoResp, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) GetGameDetail(ctx context.Context, in *GameDetailReq, opts ...grpc.CallOption) (*GameDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDetailResp)
	err := c.cc.Invoke(ctx, Game_GetGameDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) ListGames(ctx context.Context, in *ListGamesReq, opts ...grpc.CallOption) (*ListGamesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGamesResp)
	err := c.cc.Invoke(ctx, Game_ListGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetGameBasicInfo(ctx context.Context, in *GameBasicInfoReq, opts ...grpc.CallOption) (*GameBasicInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameBasicInfoResp)
	err := c.cc.Invoke(ctx, Game_GetGameBasicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
type GameServer interface {
	// 获取桌游详细信息
	GetGameDetail(context.Context, *GameDetailReq) (*GameDetailResp, error)
	// 分页查询桌游列表
	ListGames(context.Context, *ListGamesReq) (*ListGamesResp, error)
	// 获取桌游基础摘要
	GetGameBasicInfo(context.Context, *GameBasicInfoReq) (*GameBasicInfoResp, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) GetGameDetail(context.Context, *GameDetailReq) (*GameDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameDetail not implemented")
}
func (UnimplementedGameServer) ListGames(context.Context, *ListGamesReq) (*ListGamesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGames not implemented")
}
func (UnimplementedGameServer) GetGameBasicInfo(context.Context, *GameBasicInfoReq) (*GameBasicInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameBasicInfo not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call pancis, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_GetGameDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetGameDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GetGameDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetGameDetail(ctx, req.(*GameDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_ListGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).ListGames(ctx, req.(*ListGamesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetGameBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetGameBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GetGameBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetGameBasicInfo(ctx, req.(*GameBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameDetail",
			Handler:    _Game_GetGameDetail_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _Game_ListGames_Handler,
		},
		{
			MethodName: "GetGameBasicInfo",
			Handler:    _Game_GetGameBasicInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
