// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: game.proto

package game

import (
	"context"

	"dicetales.com/apps/game/rpc/game"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FilterGamesReq       = game.FilterGamesReq
	FilterGamesResp      = game.FilterGamesResp
	GameBasic            = game.GameBasic
	GameResource         = game.GameResource
	GetGameBasicInfoReq  = game.GetGameBasicInfoReq
	GetGameBasicInfoResp = game.GetGameBasicInfoResp
	GetGameDetailReq     = game.GetGameDetailReq
	GetGameDetailResp    = game.GetGameDetailResp
	SearchGamesReq       = game.SearchGamesReq
	SearchGamesResp      = game.SearchGamesResp
	Tag                  = game.Tag

	Game interface {
		// 获取桌游详细信息
		GetGameDetail(ctx context.Context, in *GetGameDetailReq, opts ...grpc.CallOption) (*GetGameDetailResp, error)
		// 高级组合筛选 (核心亮点)
		FilterGames(ctx context.Context, in *FilterGamesReq, opts ...grpc.CallOption) (*FilterGamesResp, error)
		// 模糊搜索
		SearchGames(ctx context.Context, in *SearchGamesReq, opts ...grpc.CallOption) (*SearchGamesResp, error)
		// 批量拉取桌游轻量摘要
		GetGameBasicInfo(ctx context.Context, in *GetGameBasicInfoReq, opts ...grpc.CallOption) (*GetGameBasicInfoResp, error)
	}

	defaultGame struct {
		cli zrpc.Client
	}
)

func NewGame(cli zrpc.Client) Game {
	return &defaultGame{
		cli: cli,
	}
}

// 获取桌游详细信息
func (m *defaultGame) GetGameDetail(ctx context.Context, in *GetGameDetailReq, opts ...grpc.CallOption) (*GetGameDetailResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.GetGameDetail(ctx, in, opts...)
}

// 高级组合筛选 (核心亮点)
func (m *defaultGame) FilterGames(ctx context.Context, in *FilterGamesReq, opts ...grpc.CallOption) (*FilterGamesResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.FilterGames(ctx, in, opts...)
}

// 模糊搜索
func (m *defaultGame) SearchGames(ctx context.Context, in *SearchGamesReq, opts ...grpc.CallOption) (*SearchGamesResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.SearchGames(ctx, in, opts...)
}

// 批量拉取桌游轻量摘要
func (m *defaultGame) GetGameBasicInfo(ctx context.Context, in *GetGameBasicInfoReq, opts ...grpc.CallOption) (*GetGameBasicInfoResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.GetGameBasicInfo(ctx, in, opts...)
}
