// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: game.proto

package gameclient

import (
	"context"

	"dicetales.com/apps/game/rpc/game"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryInfo      = game.CategoryInfo
	GameBasicInfoReq  = game.GameBasicInfoReq
	GameBasicInfoResp = game.GameBasicInfoResp
	GameDetailReq     = game.GameDetailReq
	GameDetailResp    = game.GameDetailResp
	GameItem          = game.GameItem
	ListGamesReq      = game.ListGamesReq
	ListGamesResp     = game.ListGamesResp

	Game interface {
		// 获取桌游详细信息
		GetGameDetail(ctx context.Context, in *GameDetailReq, opts ...grpc.CallOption) (*GameDetailResp, error)
		// 分页查询桌游列表
		ListGames(ctx context.Context, in *ListGamesReq, opts ...grpc.CallOption) (*ListGamesResp, error)
		// 获取桌游基础摘要
		GetGameBasicInfo(ctx context.Context, in *GameBasicInfoReq, opts ...grpc.CallOption) (*GameBasicInfoResp, error)
	}

	defaultGame struct {
		cli zrpc.Client
	}
)

func NewGame(cli zrpc.Client) Game {
	return &defaultGame{
		cli: cli,
	}
}

// 获取桌游详细信息
func (m *defaultGame) GetGameDetail(ctx context.Context, in *GameDetailReq, opts ...grpc.CallOption) (*GameDetailResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.GetGameDetail(ctx, in, opts...)
}

// 分页查询桌游列表
func (m *defaultGame) ListGames(ctx context.Context, in *ListGamesReq, opts ...grpc.CallOption) (*ListGamesResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.ListGames(ctx, in, opts...)
}

// 获取桌游基础摘要
func (m *defaultGame) GetGameBasicInfo(ctx context.Context, in *GameBasicInfoReq, opts ...grpc.CallOption) (*GameBasicInfoResp, error) {
	client := game.NewGameClient(m.cli.Conn())
	return client.GetGameBasicInfo(ctx, in, opts...)
}
