// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package model

import (
	"context"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

type conversationModel interface {
	Insert(ctx context.Context, data *Conversation) error
	FindOne(ctx context.Context, id int64) (*Conversation, error)
	Update(ctx context.Context, data *Conversation) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id int64) (int64, error)
}

type defaultConversationModel struct {
	conn *mon.Model
}

func newDefaultConversationModel(conn *mon.Model) *defaultConversationModel {
	return &defaultConversationModel{conn: conn}
}

func (m *defaultConversationModel) Insert(ctx context.Context, data *Conversation) error {

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultConversationModel) FindOne(ctx context.Context, id int64) (*Conversation, error) {
	var data Conversation

	err := m.conn.FindOne(ctx, &data, bson.M{"_id": id})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationModel) Update(ctx context.Context, data *Conversation) (*mongo.UpdateResult, error) {

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"": data})
	return res, err
}

func (m *defaultConversationModel) Delete(ctx context.Context, id int64) (int64, error) {

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": id})
	return res, err
}
