// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GamePlaceholderReq struct {
}

type GamePlaceholderResp struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token         string `json:"token"`  // deprecate
	Expire        int64  `json:"expire"` // deprecate
	AccessToken   string `json:"accessToken"`
	AccessExpire  int64  `json:"accessExpire"`
	RefreshToken  string `json:"refreshToken"`
	RefreshExpire int64  `json:"refreshExpire"`
}

type MeetupPlaceholderReq struct {
}

type MeetupPlaceholderResp struct {
	Msg string `json:"msg"`
}

type PostPlaceholderReq struct {
}

type PostPlaceholderResp struct {
	Msg string `json:"msg"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken   string `json:"accessToken"`
	AccessExpire  int64  `json:"accessExpire"`
	RefreshToken  string `json:"refreshToken"`
	RefreshExpire int64  `json:"refreshExpire"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Sex      byte   `json:"sex"`
	Avatar   string `json:"avatar"`
}

type RegisterResp struct {
	Token         string `json:"token"`  // deprecate
	Expire        int64  `json:"expire"` // deprecate
	AccessToken   string `json:"accessToken"`
	AccessExpire  int64  `json:"accessExpire"`
	RefreshToken  string `json:"refreshToken"`
	RefreshExpire int64  `json:"refreshExpire"`
}

type SocialPlaceholderReq struct {
}

type SocialPlaceholderResp struct {
	Msg string `json:"msg"`
}

type User struct {
	Id       string `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      byte   `json:"sex"`
	Avatar   string `json:"avatar"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Info User `json:"info"`
}
