// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: apps/social/rpc/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// model
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	AddSource     int32                  `protobuf:"varint,4,opt,name=addSource,proto3" json:"addSource,omitempty"`
	FriendUid     string                 `protobuf:"bytes,5,opt,name=friendUid,proto3" json:"friendUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{0}
}

func (x *Friend) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friend) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *Friend) GetFriendUid() string {
	if x != nil {
		return x.FriendUid
	}
	return ""
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ReqUid        string                 `protobuf:"bytes,3,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	HandleResult  int32                  `protobuf:"varint,6,opt,name=handleResult,proto3" json:"handleResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FriendRequest) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *FriendRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *FriendRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type Group struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon            string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Status          int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatorUid      string                 `protobuf:"bytes,5,opt,name=creator_uid,json=creatorUid,proto3" json:"creator_uid,omitempty"`
	GroupType       int32                  `protobuf:"varint,6,opt,name=groupType,proto3" json:"groupType,omitempty"`
	IsVerify        bool                   `protobuf:"varint,7,opt,name=isVerify,proto3" json:"isVerify,omitempty"`
	Notification    string                 `protobuf:"bytes,8,opt,name=notification,proto3" json:"notification,omitempty"`
	NotificationUid string                 `protobuf:"bytes,9,opt,name=notificationUid,proto3" json:"notificationUid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Group) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Group) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

func (x *Group) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *Group) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

func (x *Group) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *Group) GetNotificationUid() string {
	if x != nil {
		return x.NotificationUid
	}
	return ""
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleLevel     int32                  `protobuf:"varint,6,opt,name=roleLevel,proto3" json:"roleLevel,omitempty"`
	JoinTime      int64                  `protobuf:"varint,7,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,8,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,9,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,10,opt,name=operatorUid,proto3" json:"operatorUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{3}
}

func (x *GroupMember) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GroupMember) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *GroupMember) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *GroupMember) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupMember) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *GroupMember) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

// req resp
type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ReqId         string                 `protobuf:"bytes,3,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,6,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,7,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	HandleUid     string                 `protobuf:"bytes,8,opt,name=handleUid,proto3" json:"handleUid,omitempty"`
	HandleResult  int32                  `protobuf:"varint,9,opt,name=handleResult,proto3" json:"handleResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GroupRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupRequest) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupRequest) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

func (x *GroupRequest) GetHandleUid() string {
	if x != nil {
		return x.HandleUid
	}
	return ""
}

func (x *GroupRequest) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type FriendPutInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReqUid        string                 `protobuf:"bytes,2,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInReq) Reset() {
	*x = FriendPutInReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInReq) ProtoMessage() {}

func (x *FriendPutInReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInReq.ProtoReflect.Descriptor instead.
func (*FriendPutInReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{5}
}

func (x *FriendPutInReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FriendPutInReq) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *FriendPutInReq) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendPutInReq) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *FriendPutInReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type FriendPutInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInResp) Reset() {
	*x = FriendPutInResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInResp) ProtoMessage() {}

func (x *FriendPutInResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInResp.ProtoReflect.Descriptor instead.
func (*FriendPutInResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{6}
}

type FriendPutInHandleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendReqId   int32                  `protobuf:"varint,1,opt,name=friendReqId,proto3" json:"friendReqId,omitempty"`
	HandleResult  int32                  `protobuf:"varint,2,opt,name=handleResult,proto3" json:"handleResult,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	AddSource     int32                  `protobuf:"varint,4,opt,name=addSource,proto3" json:"addSource,omitempty"`
	HandleMessage string                 `protobuf:"bytes,5,opt,name=handleMessage,proto3" json:"handleMessage,omitempty"`
	HandleTime    int64                  `protobuf:"varint,6,opt,name=handleTime,proto3" json:"handleTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInHandleReq) Reset() {
	*x = FriendPutInHandleReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInHandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInHandleReq) ProtoMessage() {}

func (x *FriendPutInHandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInHandleReq.ProtoReflect.Descriptor instead.
func (*FriendPutInHandleReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{7}
}

func (x *FriendPutInHandleReq) GetFriendReqId() int32 {
	if x != nil {
		return x.FriendReqId
	}
	return 0
}

func (x *FriendPutInHandleReq) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

func (x *FriendPutInHandleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendPutInHandleReq) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

func (x *FriendPutInHandleReq) GetHandleMessage() string {
	if x != nil {
		return x.HandleMessage
	}
	return ""
}

func (x *FriendPutInHandleReq) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

type FriendPutInHandleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInHandleResp) Reset() {
	*x = FriendPutInHandleResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInHandleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInHandleResp) ProtoMessage() {}

func (x *FriendPutInHandleResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInHandleResp.ProtoReflect.Descriptor instead.
func (*FriendPutInHandleResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{8}
}

type FriendPutInListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInListReq) Reset() {
	*x = FriendPutInListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInListReq) ProtoMessage() {}

func (x *FriendPutInListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInListReq.ProtoReflect.Descriptor instead.
func (*FriendPutInListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{9}
}

func (x *FriendPutInListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type FriendPutInListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqList       []*FriendRequest       `protobuf:"bytes,1,rep,name=reqList,proto3" json:"reqList,omitempty"`
	RecvList      []*FriendRequest       `protobuf:"bytes,2,rep,name=recvList,proto3" json:"recvList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPutInListResp) Reset() {
	*x = FriendPutInListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPutInListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPutInListResp) ProtoMessage() {}

func (x *FriendPutInListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPutInListResp.ProtoReflect.Descriptor instead.
func (*FriendPutInListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{10}
}

func (x *FriendPutInListResp) GetReqList() []*FriendRequest {
	if x != nil {
		return x.ReqList
	}
	return nil
}

func (x *FriendPutInListResp) GetRecvList() []*FriendRequest {
	if x != nil {
		return x.RecvList
	}
	return nil
}

type FriendListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListReq) Reset() {
	*x = FriendListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReq) ProtoMessage() {}

func (x *FriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReq.ProtoReflect.Descriptor instead.
func (*FriendListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{11}
}

func (x *FriendListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type FriendListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Friend              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListResp) Reset() {
	*x = FriendListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResp) ProtoMessage() {}

func (x *FriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResp.ProtoReflect.Descriptor instead.
func (*FriendListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{12}
}

func (x *FriendListResp) GetList() []*Friend {
	if x != nil {
		return x.List
	}
	return nil
}

type FriendDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FriendUid     string                 `protobuf:"bytes,2,opt,name=friendUid,proto3" json:"friendUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendDeleteReq) Reset() {
	*x = FriendDeleteReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendDeleteReq) ProtoMessage() {}

func (x *FriendDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendDeleteReq.ProtoReflect.Descriptor instead.
func (*FriendDeleteReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{13}
}

func (x *FriendDeleteReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FriendDeleteReq) GetFriendUid() string {
	if x != nil {
		return x.FriendUid
	}
	return ""
}

type FriendDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendDeleteResp) Reset() {
	*x = FriendDeleteResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendDeleteResp) ProtoMessage() {}

func (x *FriendDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendDeleteResp.ProtoReflect.Descriptor instead.
func (*FriendDeleteResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{14}
}

// 群
type GroupCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	IsVerify      bool                   `protobuf:"varint,3,opt,name=isVerify,proto3" json:"isVerify,omitempty"`
	CreatorUid    string                 `protobuf:"bytes,4,opt,name=creatorUid,proto3" json:"creatorUid,omitempty"`
	GroupType     int32                  `protobuf:"varint,5,opt,name=groupType,proto3" json:"groupType,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateReq) Reset() {
	*x = GroupCreateReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateReq) ProtoMessage() {}

func (x *GroupCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateReq.ProtoReflect.Descriptor instead.
func (*GroupCreateReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{15}
}

func (x *GroupCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupCreateReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GroupCreateReq) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

func (x *GroupCreateReq) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

func (x *GroupCreateReq) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GroupCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateResp) Reset() {
	*x = GroupCreateResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResp) ProtoMessage() {}

func (x *GroupCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateResp.ProtoReflect.Descriptor instead.
func (*GroupCreateResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{16}
}

func (x *GroupCreateResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GroupPutinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	ReqUid        string                 `protobuf:"bytes,2,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=reqMsg,proto3" json:"reqMsg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
	JoinSource    int32                  `protobuf:"varint,5,opt,name=joinSource,proto3" json:"joinSource,omitempty"`
	InviterUid    string                 `protobuf:"bytes,6,opt,name=inviterUid,proto3" json:"inviterUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutinReq) Reset() {
	*x = GroupPutinReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutinReq) ProtoMessage() {}

func (x *GroupPutinReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutinReq.ProtoReflect.Descriptor instead.
func (*GroupPutinReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{17}
}

func (x *GroupPutinReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPutinReq) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *GroupPutinReq) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupPutinReq) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupPutinReq) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupPutinReq) GetInviterUid() string {
	if x != nil {
		return x.InviterUid
	}
	return ""
}

type GroupPutinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutinResp) Reset() {
	*x = GroupPutinResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutinResp) ProtoMessage() {}

func (x *GroupPutinResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutinResp.ProtoReflect.Descriptor instead.
func (*GroupPutinResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{18}
}

func (x *GroupPutinResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupPutinListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutinListReq) Reset() {
	*x = GroupPutinListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutinListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutinListReq) ProtoMessage() {}

func (x *GroupPutinListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutinListReq.ProtoReflect.Descriptor instead.
func (*GroupPutinListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{19}
}

func (x *GroupPutinListReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupPutinListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupRequest        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutinListResp) Reset() {
	*x = GroupPutinListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutinListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutinListResp) ProtoMessage() {}

func (x *GroupPutinListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutinListResp.ProtoReflect.Descriptor instead.
func (*GroupPutinListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{20}
}

func (x *GroupPutinListResp) GetList() []*GroupRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupPutInHandleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupReqId    int32                  `protobuf:"varint,1,opt,name=groupReqId,proto3" json:"groupReqId,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	HandleUid     string                 `protobuf:"bytes,3,opt,name=handleUid,proto3" json:"handleUid,omitempty"`
	HandleResult  int32                  `protobuf:"varint,4,opt,name=handleResult,proto3" json:"handleResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInHandleReq) Reset() {
	*x = GroupPutInHandleReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInHandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInHandleReq) ProtoMessage() {}

func (x *GroupPutInHandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInHandleReq.ProtoReflect.Descriptor instead.
func (*GroupPutInHandleReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{21}
}

func (x *GroupPutInHandleReq) GetGroupReqId() int32 {
	if x != nil {
		return x.GroupReqId
	}
	return 0
}

func (x *GroupPutInHandleReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPutInHandleReq) GetHandleUid() string {
	if x != nil {
		return x.HandleUid
	}
	return ""
}

func (x *GroupPutInHandleReq) GetHandleResult() int32 {
	if x != nil {
		return x.HandleResult
	}
	return 0
}

type GroupPutInHandleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPutInHandleResp) Reset() {
	*x = GroupPutInHandleResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPutInHandleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPutInHandleResp) ProtoMessage() {}

func (x *GroupPutInHandleResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPutInHandleResp.ProtoReflect.Descriptor instead.
func (*GroupPutInHandleResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{22}
}

func (x *GroupPutInHandleResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListReq) Reset() {
	*x = GroupListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListReq) ProtoMessage() {}

func (x *GroupListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListReq.ProtoReflect.Descriptor instead.
func (*GroupListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{23}
}

func (x *GroupListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GroupListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Group               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResp) Reset() {
	*x = GroupListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResp) ProtoMessage() {}

func (x *GroupListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResp.ProtoReflect.Descriptor instead.
func (*GroupListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{24}
}

func (x *GroupListResp) GetList() []*Group {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberReq) Reset() {
	*x = GroupMemberReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberReq) ProtoMessage() {}

func (x *GroupMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberReq.ProtoReflect.Descriptor instead.
func (*GroupMemberReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{25}
}

func (x *GroupMemberReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupMemberResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupMember         `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberResp) Reset() {
	*x = GroupMemberResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberResp) ProtoMessage() {}

func (x *GroupMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberResp.ProtoReflect.Descriptor instead.
func (*GroupMemberResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{26}
}

func (x *GroupMemberResp) GetList() []*GroupMember {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupUserReqListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserReqListReq) Reset() {
	*x = GroupUserReqListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserReqListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserReqListReq) ProtoMessage() {}

func (x *GroupUserReqListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserReqListReq.ProtoReflect.Descriptor instead.
func (*GroupUserReqListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{27}
}

func (x *GroupUserReqListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GroupUserReqListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GroupRequest        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserReqListResp) Reset() {
	*x = GroupUserReqListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserReqListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserReqListResp) ProtoMessage() {}

func (x *GroupUserReqListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserReqListResp.ProtoReflect.Descriptor instead.
func (*GroupUserReqListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{28}
}

func (x *GroupUserReqListResp) GetList() []*GroupRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type GroupQuitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupQuitReq) Reset() {
	*x = GroupQuitReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupQuitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupQuitReq) ProtoMessage() {}

func (x *GroupQuitReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupQuitReq.ProtoReflect.Descriptor instead.
func (*GroupQuitReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{29}
}

func (x *GroupQuitReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupQuitReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GroupQuitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupQuitResp) Reset() {
	*x = GroupQuitResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupQuitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupQuitResp) ProtoMessage() {}

func (x *GroupQuitResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupQuitResp.ProtoReflect.Descriptor instead.
func (*GroupQuitResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{30}
}

func (x *GroupQuitResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupModifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	IsVerify      bool                   `protobuf:"varint,4,opt,name=isVerify,proto3" json:"isVerify,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupModifyReq) Reset() {
	*x = GroupModifyReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupModifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupModifyReq) ProtoMessage() {}

func (x *GroupModifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupModifyReq.ProtoReflect.Descriptor instead.
func (*GroupModifyReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{31}
}

func (x *GroupModifyReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupModifyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupModifyReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GroupModifyReq) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

func (x *GroupModifyReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GroupModifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupModifyResp) Reset() {
	*x = GroupModifyResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupModifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupModifyResp) ProtoMessage() {}

func (x *GroupModifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupModifyResp.ProtoReflect.Descriptor instead.
func (*GroupModifyResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{32}
}

func (x *GroupModifyResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupNotificationModifyReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Notification    string                 `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	NotificationUid string                 `protobuf:"bytes,3,opt,name=notificationUid,proto3" json:"notificationUid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupNotificationModifyReq) Reset() {
	*x = GroupNotificationModifyReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNotificationModifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNotificationModifyReq) ProtoMessage() {}

func (x *GroupNotificationModifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNotificationModifyReq.ProtoReflect.Descriptor instead.
func (*GroupNotificationModifyReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{33}
}

func (x *GroupNotificationModifyReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupNotificationModifyReq) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *GroupNotificationModifyReq) GetNotificationUid() string {
	if x != nil {
		return x.NotificationUid
	}
	return ""
}

type GroupNotificationModifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupNotificationModifyResp) Reset() {
	*x = GroupNotificationModifyResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNotificationModifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNotificationModifyResp) ProtoMessage() {}

func (x *GroupNotificationModifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNotificationModifyResp.ProtoReflect.Descriptor instead.
func (*GroupNotificationModifyResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{34}
}

func (x *GroupNotificationModifyResp) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_apps_social_rpc_social_proto protoreflect.FileDescriptor

const file_apps_social_rpc_social_proto_rawDesc = "" +
	"\n" +
	"\x1capps/social/rpc/social.proto\x12\x06social\"~\n" +
	"\x06Friend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1c\n" +
	"\taddSource\x18\x04 \x01(\x05R\taddSource\x12\x1c\n" +
	"\tfriendUid\x18\x05 \x01(\tR\tfriendUid\"\x9f\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06reqUid\x18\x03 \x01(\tR\x06reqUid\x12\x16\n" +
	"\x06reqMsg\x18\x04 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x05 \x01(\x03R\areqTime\x12\"\n" +
	"\fhandleResult\x18\x06 \x01(\x05R\fhandleResult\"\x80\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreator_uid\x18\x05 \x01(\tR\n" +
	"creatorUid\x12\x1c\n" +
	"\tgroupType\x18\x06 \x01(\x05R\tgroupType\x12\x1a\n" +
	"\bisVerify\x18\a \x01(\bR\bisVerify\x12\"\n" +
	"\fnotification\x18\b \x01(\tR\fnotification\x12(\n" +
	"\x0fnotificationUid\x18\t \x01(\tR\x0fnotificationUid\"\xe5\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x1c\n" +
	"\troleLevel\x18\x06 \x01(\x05R\troleLevel\x12\x1a\n" +
	"\bjoinTime\x18\a \x01(\x03R\bjoinTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\b \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\t \x01(\tR\n" +
	"inviterUid\x12 \n" +
	"\voperatorUid\x18\n" +
	" \x01(\tR\voperatorUid\"\x82\x02\n" +
	"\fGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x14\n" +
	"\x05reqId\x18\x03 \x01(\tR\x05reqId\x12\x16\n" +
	"\x06reqMsg\x18\x04 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x05 \x01(\x03R\areqTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\x06 \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\a \x01(\tR\n" +
	"inviterUid\x12\x1c\n" +
	"\thandleUid\x18\b \x01(\tR\thandleUid\x12\"\n" +
	"\fhandleResult\x18\t \x01(\x05R\fhandleResult\"\x84\x01\n" +
	"\x0eFriendPutInReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x16\n" +
	"\x06reqUid\x18\x02 \x01(\tR\x06reqUid\x12\x16\n" +
	"\x06reqMsg\x18\x03 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x04 \x01(\x03R\areqTime\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"\x11\n" +
	"\x0fFriendPutInResp\"\xd8\x01\n" +
	"\x14FriendPutInHandleReq\x12 \n" +
	"\vfriendReqId\x18\x01 \x01(\x05R\vfriendReqId\x12\"\n" +
	"\fhandleResult\x18\x02 \x01(\x05R\fhandleResult\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1c\n" +
	"\taddSource\x18\x04 \x01(\x05R\taddSource\x12$\n" +
	"\rhandleMessage\x18\x05 \x01(\tR\rhandleMessage\x12\x1e\n" +
	"\n" +
	"handleTime\x18\x06 \x01(\x03R\n" +
	"handleTime\"\x17\n" +
	"\x15FriendPutInHandleResp\"&\n" +
	"\x12FriendPutInListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"y\n" +
	"\x13FriendPutInListResp\x12/\n" +
	"\areqList\x18\x01 \x03(\v2\x15.social.FriendRequestR\areqList\x121\n" +
	"\brecvList\x18\x02 \x03(\v2\x15.social.FriendRequestR\brecvList\"!\n" +
	"\rFriendListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"4\n" +
	"\x0eFriendListResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.social.FriendR\x04list\"A\n" +
	"\x0fFriendDeleteReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\tfriendUid\x18\x02 \x01(\tR\tfriendUid\"\x12\n" +
	"\x10FriendDeleteResp\"\xb4\x01\n" +
	"\x0eGroupCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x1a\n" +
	"\bisVerify\x18\x03 \x01(\bR\bisVerify\x12\x1e\n" +
	"\n" +
	"creatorUid\x18\x04 \x01(\tR\n" +
	"creatorUid\x12\x1c\n" +
	"\tgroupType\x18\x05 \x01(\x05R\tgroupType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"!\n" +
	"\x0fGroupCreateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb3\x01\n" +
	"\rGroupPutinReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06reqUid\x18\x02 \x01(\tR\x06reqUid\x12\x16\n" +
	"\x06reqMsg\x18\x03 \x01(\tR\x06reqMsg\x12\x18\n" +
	"\areqTime\x18\x04 \x01(\x03R\areqTime\x12\x1e\n" +
	"\n" +
	"joinSource\x18\x05 \x01(\x05R\n" +
	"joinSource\x12\x1e\n" +
	"\n" +
	"inviterUid\x18\x06 \x01(\tR\n" +
	"inviterUid\"*\n" +
	"\x0eGroupPutinResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"-\n" +
	"\x11GroupPutinListReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\">\n" +
	"\x12GroupPutinListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.social.GroupRequestR\x04list\"\x91\x01\n" +
	"\x13GroupPutInHandleReq\x12\x1e\n" +
	"\n" +
	"groupReqId\x18\x01 \x01(\x05R\n" +
	"groupReqId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\tR\agroupId\x12\x1c\n" +
	"\thandleUid\x18\x03 \x01(\tR\thandleUid\x12\"\n" +
	"\fhandleResult\x18\x04 \x01(\x05R\fhandleResult\"0\n" +
	"\x14GroupPutInHandleResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\" \n" +
	"\fGroupListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"2\n" +
	"\rGroupListResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.social.GroupR\x04list\"*\n" +
	"\x0eGroupMemberReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\":\n" +
	"\x0fGroupMemberResp\x12'\n" +
	"\x04List\x18\x01 \x03(\v2\x13.social.GroupMemberR\x04List\"'\n" +
	"\x13GroupUserReqListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"@\n" +
	"\x14GroupUserReqListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.social.GroupRequestR\x04list\":\n" +
	"\fGroupQuitReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\")\n" +
	"\rGroupQuitResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"\x90\x01\n" +
	"\x0eGroupModifyReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1a\n" +
	"\bisVerify\x18\x04 \x01(\bR\bisVerify\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"+\n" +
	"\x0fGroupModifyResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\"\x84\x01\n" +
	"\x1aGroupNotificationModifyReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\"\n" +
	"\fnotification\x18\x02 \x01(\tR\fnotification\x12(\n" +
	"\x0fnotificationUid\x18\x03 \x01(\tR\x0fnotificationUid\"7\n" +
	"\x1bGroupNotificationModifyResp\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId2\xa2\b\n" +
	"\x06social\x12>\n" +
	"\vFriendPutIn\x12\x16.social.FriendPutInReq\x1a\x17.social.FriendPutInResp\x12P\n" +
	"\x11FriendPutInHandle\x12\x1c.social.FriendPutInHandleReq\x1a\x1d.social.FriendPutInHandleResp\x12J\n" +
	"\x0fFriendPutInList\x12\x1a.social.FriendPutInListReq\x1a\x1b.social.FriendPutInListResp\x12;\n" +
	"\n" +
	"FriendList\x12\x15.social.FriendListReq\x1a\x16.social.FriendListResp\x12A\n" +
	"\fFriendDelete\x12\x17.social.FriendDeleteReq\x1a\x18.social.FriendDeleteResp\x12>\n" +
	"\vGroupCreate\x12\x16.social.GroupCreateReq\x1a\x17.social.GroupCreateResp\x12;\n" +
	"\n" +
	"GroupPutin\x12\x15.social.GroupPutinReq\x1a\x16.social.GroupPutinResp\x12G\n" +
	"\x0eGroupPutinList\x12\x19.social.GroupPutinListReq\x1a\x1a.social.GroupPutinListResp\x12M\n" +
	"\x10GroupUserReqList\x12\x1b.social.GroupUserReqListReq\x1a\x1c.social.GroupUserReqListResp\x12M\n" +
	"\x10GroupPutInHandle\x12\x1b.social.GroupPutInHandleReq\x1a\x1c.social.GroupPutInHandleResp\x128\n" +
	"\tGroupList\x12\x14.social.GroupListReq\x1a\x15.social.GroupListResp\x12>\n" +
	"\vGroupMember\x12\x16.social.GroupMemberReq\x1a\x17.social.GroupMemberResp\x128\n" +
	"\tGroupQuit\x12\x14.social.GroupQuitReq\x1a\x15.social.GroupQuitResp\x12>\n" +
	"\vGroupModify\x12\x16.social.GroupModifyReq\x1a\x17.social.GroupModifyResp\x12b\n" +
	"\x17GroupNotificationModify\x12\".social.GroupNotificationModifyReq\x1a#.social.GroupNotificationModifyRespB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_apps_social_rpc_social_proto_rawDescOnce sync.Once
	file_apps_social_rpc_social_proto_rawDescData []byte
)

func file_apps_social_rpc_social_proto_rawDescGZIP() []byte {
	file_apps_social_rpc_social_proto_rawDescOnce.Do(func() {
		file_apps_social_rpc_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)))
	})
	return file_apps_social_rpc_social_proto_rawDescData
}

var file_apps_social_rpc_social_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_apps_social_rpc_social_proto_goTypes = []any{
	(*Friend)(nil),                      // 0: social.Friend
	(*FriendRequest)(nil),               // 1: social.FriendRequest
	(*Group)(nil),                       // 2: social.Group
	(*GroupMember)(nil),                 // 3: social.GroupMember
	(*GroupRequest)(nil),                // 4: social.GroupRequest
	(*FriendPutInReq)(nil),              // 5: social.FriendPutInReq
	(*FriendPutInResp)(nil),             // 6: social.FriendPutInResp
	(*FriendPutInHandleReq)(nil),        // 7: social.FriendPutInHandleReq
	(*FriendPutInHandleResp)(nil),       // 8: social.FriendPutInHandleResp
	(*FriendPutInListReq)(nil),          // 9: social.FriendPutInListReq
	(*FriendPutInListResp)(nil),         // 10: social.FriendPutInListResp
	(*FriendListReq)(nil),               // 11: social.FriendListReq
	(*FriendListResp)(nil),              // 12: social.FriendListResp
	(*FriendDeleteReq)(nil),             // 13: social.FriendDeleteReq
	(*FriendDeleteResp)(nil),            // 14: social.FriendDeleteResp
	(*GroupCreateReq)(nil),              // 15: social.GroupCreateReq
	(*GroupCreateResp)(nil),             // 16: social.GroupCreateResp
	(*GroupPutinReq)(nil),               // 17: social.GroupPutinReq
	(*GroupPutinResp)(nil),              // 18: social.GroupPutinResp
	(*GroupPutinListReq)(nil),           // 19: social.GroupPutinListReq
	(*GroupPutinListResp)(nil),          // 20: social.GroupPutinListResp
	(*GroupPutInHandleReq)(nil),         // 21: social.GroupPutInHandleReq
	(*GroupPutInHandleResp)(nil),        // 22: social.GroupPutInHandleResp
	(*GroupListReq)(nil),                // 23: social.GroupListReq
	(*GroupListResp)(nil),               // 24: social.GroupListResp
	(*GroupMemberReq)(nil),              // 25: social.GroupMemberReq
	(*GroupMemberResp)(nil),             // 26: social.GroupMemberResp
	(*GroupUserReqListReq)(nil),         // 27: social.GroupUserReqListReq
	(*GroupUserReqListResp)(nil),        // 28: social.GroupUserReqListResp
	(*GroupQuitReq)(nil),                // 29: social.GroupQuitReq
	(*GroupQuitResp)(nil),               // 30: social.GroupQuitResp
	(*GroupModifyReq)(nil),              // 31: social.GroupModifyReq
	(*GroupModifyResp)(nil),             // 32: social.GroupModifyResp
	(*GroupNotificationModifyReq)(nil),  // 33: social.GroupNotificationModifyReq
	(*GroupNotificationModifyResp)(nil), // 34: social.GroupNotificationModifyResp
}
var file_apps_social_rpc_social_proto_depIdxs = []int32{
	1,  // 0: social.FriendPutInListResp.reqList:type_name -> social.FriendRequest
	1,  // 1: social.FriendPutInListResp.recvList:type_name -> social.FriendRequest
	0,  // 2: social.FriendListResp.list:type_name -> social.Friend
	4,  // 3: social.GroupPutinListResp.list:type_name -> social.GroupRequest
	2,  // 4: social.GroupListResp.list:type_name -> social.Group
	3,  // 5: social.GroupMemberResp.List:type_name -> social.GroupMember
	4,  // 6: social.GroupUserReqListResp.list:type_name -> social.GroupRequest
	5,  // 7: social.social.FriendPutIn:input_type -> social.FriendPutInReq
	7,  // 8: social.social.FriendPutInHandle:input_type -> social.FriendPutInHandleReq
	9,  // 9: social.social.FriendPutInList:input_type -> social.FriendPutInListReq
	11, // 10: social.social.FriendList:input_type -> social.FriendListReq
	13, // 11: social.social.FriendDelete:input_type -> social.FriendDeleteReq
	15, // 12: social.social.GroupCreate:input_type -> social.GroupCreateReq
	17, // 13: social.social.GroupPutin:input_type -> social.GroupPutinReq
	19, // 14: social.social.GroupPutinList:input_type -> social.GroupPutinListReq
	27, // 15: social.social.GroupUserReqList:input_type -> social.GroupUserReqListReq
	21, // 16: social.social.GroupPutInHandle:input_type -> social.GroupPutInHandleReq
	23, // 17: social.social.GroupList:input_type -> social.GroupListReq
	25, // 18: social.social.GroupMember:input_type -> social.GroupMemberReq
	29, // 19: social.social.GroupQuit:input_type -> social.GroupQuitReq
	31, // 20: social.social.GroupModify:input_type -> social.GroupModifyReq
	33, // 21: social.social.GroupNotificationModify:input_type -> social.GroupNotificationModifyReq
	6,  // 22: social.social.FriendPutIn:output_type -> social.FriendPutInResp
	8,  // 23: social.social.FriendPutInHandle:output_type -> social.FriendPutInHandleResp
	10, // 24: social.social.FriendPutInList:output_type -> social.FriendPutInListResp
	12, // 25: social.social.FriendList:output_type -> social.FriendListResp
	14, // 26: social.social.FriendDelete:output_type -> social.FriendDeleteResp
	16, // 27: social.social.GroupCreate:output_type -> social.GroupCreateResp
	18, // 28: social.social.GroupPutin:output_type -> social.GroupPutinResp
	20, // 29: social.social.GroupPutinList:output_type -> social.GroupPutinListResp
	28, // 30: social.social.GroupUserReqList:output_type -> social.GroupUserReqListResp
	22, // 31: social.social.GroupPutInHandle:output_type -> social.GroupPutInHandleResp
	24, // 32: social.social.GroupList:output_type -> social.GroupListResp
	26, // 33: social.social.GroupMember:output_type -> social.GroupMemberResp
	30, // 34: social.social.GroupQuit:output_type -> social.GroupQuitResp
	32, // 35: social.social.GroupModify:output_type -> social.GroupModifyResp
	34, // 36: social.social.GroupNotificationModify:output_type -> social.GroupNotificationModifyResp
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_apps_social_rpc_social_proto_init() }
func file_apps_social_rpc_social_proto_init() {
	if File_apps_social_rpc_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_social_rpc_social_proto_goTypes,
		DependencyIndexes: file_apps_social_rpc_social_proto_depIdxs,
		MessageInfos:      file_apps_social_rpc_social_proto_msgTypes,
	}.Build()
	File_apps_social_rpc_social_proto = out.File
	file_apps_social_rpc_social_proto_goTypes = nil
	file_apps_social_rpc_social_proto_depIdxs = nil
}
