// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendRequestFieldNames          = builder.RawFieldNames(&FriendRequest{})
	friendRequestRows                = strings.Join(friendRequestFieldNames, ",")
	friendRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestIdPrefix = "cache:friendRequest:id:"
)

type (
	friendRequestModel interface {
		Insert(ctx context.Context, data *FriendRequest) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FriendRequest, error)
		Update(ctx context.Context, data *FriendRequest) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFriendRequestModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequest struct {
		Id           uint64         `db:"id"`
		Uid          string         `db:"uid"`
		ReqUid       string         `db:"req_uid"`
		ReqMsg       sql.NullString `db:"req_msg"`
		ReqTime      time.Time      `db:"req_time"`
		ReqRemark    string         `db:"req_remark"`
		HandleResult sql.NullInt64  `db:"handle_result"`
		HandleMsg    sql.NullString `db:"handle_msg"`
		HandledAt    sql.NullTime   `db:"handled_at"`
	}
)

func newFriendRequestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestModel {
	return &defaultFriendRequestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_request`",
	}
}

func (m *defaultFriendRequestModel) Delete(ctx context.Context, id uint64) error {
	friendRequestIdKey := fmt.Sprintf("%s%v", cacheFriendRequestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestIdKey)
	return err
}

func (m *defaultFriendRequestModel) FindOne(ctx context.Context, id uint64) (*FriendRequest, error) {
	friendRequestIdKey := fmt.Sprintf("%s%v", cacheFriendRequestIdPrefix, id)
	var resp FriendRequest
	err := m.QueryRowCtx(ctx, &resp, friendRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestModel) Insert(ctx context.Context, data *FriendRequest) (sql.Result, error) {
	friendRequestIdKey := fmt.Sprintf("%s%v", cacheFriendRequestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, friendRequestRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.ReqUid, data.ReqMsg, data.ReqTime, data.ReqRemark, data.HandleResult, data.HandleMsg, data.HandledAt)
	}, friendRequestIdKey)
	return ret, err
}

func (m *defaultFriendRequestModel) Update(ctx context.Context, data *FriendRequest) error {
	friendRequestIdKey := fmt.Sprintf("%s%v", cacheFriendRequestIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.ReqUid, data.ReqMsg, data.ReqTime, data.ReqRemark, data.HandleResult, data.HandleMsg, data.HandledAt, data.Id)
	}, friendRequestIdKey)
	return err
}

func (m *defaultFriendRequestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestIdPrefix, primary)
}

func (m *defaultFriendRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestModel) tableName() string {
	return m.table
}
