// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: post.proto

package postservice

import (
	"context"

	"dicetales.com/apps/post/rpc/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentPreview        = post.CommentPreview
	CreateCommentReq      = post.CreateCommentReq
	CreateCommentResp     = post.CreateCommentResp
	CreatePostReq         = post.CreatePostReq
	CreatePostResp        = post.CreatePostResp
	GetFriendTimelineReq  = post.GetFriendTimelineReq
	GetFriendTimelineResp = post.GetFriendTimelineResp
	GetPostDetailReq      = post.GetPostDetailReq
	GetPostDetailResp     = post.GetPostDetailResp
	GetPublicTimelineReq  = post.GetPublicTimelineReq
	GetPublicTimelineResp = post.GetPublicTimelineResp
	InteractReq           = post.InteractReq
	InteractResp          = post.InteractResp
	PostDetail            = post.PostDetail
	PostInfo              = post.PostInfo

	PostService interface {
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		GetFriendTimeline(ctx context.Context, in *GetFriendTimelineReq, opts ...grpc.CallOption) (*GetFriendTimelineResp, error)
		GetPublicTimeline(ctx context.Context, in *GetPublicTimelineReq, opts ...grpc.CallOption) (*GetPublicTimelineResp, error)
		Interact(ctx context.Context, in *InteractReq, opts ...grpc.CallOption) (*InteractResp, error)
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error)
	}

	defaultPostService struct {
		cli zrpc.Client
	}
)

func NewPostService(cli zrpc.Client) PostService {
	return &defaultPostService{
		cli: cli,
	}
}

func (m *defaultPostService) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

func (m *defaultPostService) GetFriendTimeline(ctx context.Context, in *GetFriendTimelineReq, opts ...grpc.CallOption) (*GetFriendTimelineResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetFriendTimeline(ctx, in, opts...)
}

func (m *defaultPostService) GetPublicTimeline(ctx context.Context, in *GetPublicTimelineReq, opts ...grpc.CallOption) (*GetPublicTimelineResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetPublicTimeline(ctx, in, opts...)
}

func (m *defaultPostService) Interact(ctx context.Context, in *InteractReq, opts ...grpc.CallOption) (*InteractResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.Interact(ctx, in, opts...)
}

func (m *defaultPostService) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultPostService) GetPostDetail(ctx context.Context, in *GetPostDetailReq, opts ...grpc.CallOption) (*GetPostDetailResp, error) {
	client := post.NewPostServiceClient(m.cli.Conn())
	return client.GetPostDetail(ctx, in, opts...)
}
