// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: post.proto

package server

import (
	"context"

	"dicetales.com/apps/post/rpc/internal/logic"
	"dicetales.com/apps/post/rpc/internal/svc"
	"dicetales.com/apps/post/rpc/post"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServiceServer) CreatePost(ctx context.Context, in *post.CreatePostReq) (*post.CreatePostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostServiceServer) GetFriendTimeline(ctx context.Context, in *post.GetFriendTimelineReq) (*post.GetFriendTimelineResp, error) {
	l := logic.NewGetFriendTimelineLogic(ctx, s.svcCtx)
	return l.GetFriendTimeline(in)
}

func (s *PostServiceServer) GetPublicTimeline(ctx context.Context, in *post.GetPublicTimelineReq) (*post.GetPublicTimelineResp, error) {
	l := logic.NewGetPublicTimelineLogic(ctx, s.svcCtx)
	return l.GetPublicTimeline(in)
}

func (s *PostServiceServer) Interact(ctx context.Context, in *post.InteractReq) (*post.InteractResp, error) {
	l := logic.NewInteractLogic(ctx, s.svcCtx)
	return l.Interact(in)
}

func (s *PostServiceServer) CreateComment(ctx context.Context, in *post.CreateCommentReq) (*post.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *PostServiceServer) GetPostDetail(ctx context.Context, in *post.GetPostDetailReq) (*post.GetPostDetailResp, error) {
	l := logic.NewGetPostDetailLogic(ctx, s.svcCtx)
	return l.GetPostDetail(in)
}
